// ==UserScript==
// @name                L4 WME Validator Localization for Czech Republic
// @version             1.1.18
// @description         This script localizes WME Validator for Czech Republic. You also need main package (WME Validator) installed.
// @match               https://editor-beta.waze.com/*editor/*
// @match               https://www.waze.com/*editor/*
// @grant               none
// @run-at              document-start
// @namespace           https://greasyfork.org/users/3173
// ==/UserScript==
//
/*
  Please translate all the lines marked with "TODO: "
  Please DO NOT change ".en" properties. To override english text use "titleEN",
  "problemEN" and "solutionEN" check params (see an example below).

  See Settings->About->Available checks for complete list of checks and their params.

  Examples:

  Enable #170 "Lowercase street name" but allow lowercase "exit" and "to":
    "170.enabled": true,
    "170.params": {
        "regexp": "/^((exit|to) )?[a-z]/",
    "},

  Enable #130 "Custom check" to find a dot in street names, but allow dots at Ramps:
    "130.enabled": true,
    "130.params": {
        "titleEN": "Street name with a dot",
        "problemEN": "There is a dot in the street name (excluding Ramps)",
        "solutionEN": "Expand the abbreviation or remove the dot",
        "template": "${type}:${street}",
        "regexp": "D/^[^4][0-9]?:.*\\./",
    },
    *Note: use D at the beginning of RegExp to enable debugging on JS console.
    *Note: do not forget to escape backslashes in strings, i.e. use "\\" instead of "\".
*/

window.WME_Validator_Czech_Republic = {
  ".country": "Czech Republic",
  ".codeISO": "CZ",
  ".author": "Kebb01, petrjanik, Zirland, pvo11, d2-mac",
  ".updated": "2015-12-21",
  ".link": "https://greasyfork.org/cs/scripts/8476-l4-wme-validator-localization-for-czech-republic",
  ".lng": "CS",
  "city.consider.en": "consider this city name:",
  "city.consider": "zvažte tento název města:",
  "city.1.en": "city name is too short",
  "city.1": "název města je příliš krátký",
  "city.2.en": "expand the abbreviation",
  "city.2": "rozepište zkratku",
  "city.3.en": "complete short name",
  "city.3": "dokončete krátký název",
  "city.4.en": "complete city name",
  "city.4": "dokončete jméno města",
  "city.5.en": "correct letter case",
  "city.5": "opravte velikost písmena",
  "city.6.en": "check word order",
  "city.6": "zkontrolujte slovosled",
  "city.7.en": "check abbreviations",
  "city.7": "zkontrolujte zkratku",
  "city.8a.en": "add county name",
  "city.8a": "přidejte název okresu",
  "city.8r.en": "remove county name",
  "city.8r": "odstraňte název okresu",
  "city.9.en": "check county name",
  "city.9": "zkontrolujte název okresu",
  "city.10a.en": "add a word",
  "city.10a": "přidejte slovo",
  "city.10r.en": "remove a word",
  "city.10r": "odstraňte slovo",
  "city.11.en": "add county code",
  "city.11": "přidejte kód okresu",
  "city.12.en": "identical names, but different city IDs",
  "city.12": "totožné názvy, ale odlišné ID měst",
  "city.13a.en": "add a space",
  "city.13a": "přidejte mezeru",
  "city.13r.en": "remove a space",
  "city.13r": "odstraňte mezeru",
  "city.14.en": "check the number",
  "city.14": "zkontrolujte číslo",
  "props.skipped.title.en": "The segment is not checked",
  "props.skipped.title": "Segment není zkontrolován",
  "props.skipped.problem.en": "The segment is modified after 2014-05-01 AND locked for you, so Validator did not check it",
  "props.skipped.problem": "Segment byl upraven po 1. květnu 2014 a je pro vás uzamčen. Validátor ho proto nezkontroluje",
  "err.regexp.en": "Error parsing option for check #${n}:",
  "err.regexp": "Možná chyba nastavení při analýze #${n}:",
  "props.disabled.en": "WME Validator is disabled",
  "props.disabled": "WME Validátor je vypnutý",
  "props.limit.title.en": "Too many issues reported",
  "props.limit.title": "Je hlášeno přiliš mnoho chyb",
  "props.limit.problem.en": "There are too many issues reported, so some of them might not be shown",
  "props.limit.problem": "Existuje příliš mnoho nahlášených chyb, takže některé z nich nemusí být zobrazeny",
  "props.limit.solution.en": "Deselect the segment and stop scanning process. Then click red '✘' (Clear report) button",
  "props.limit.solution": "Odznačte segment a zastavte proces skenování. Pak klikněte na červené tlačítko '✘' (Vyčistit hlášení)",
  "props.reports.en": "reports",
  "props.reports": "hlášení",
  "props.noneditable.en": "You cannot edit this segment",
  "props.noneditable": "Tento segment nemůžete editovat",
  "report.save.en": "Save this report",
  "report.save": "Uložit toto hlášení",
  "report.list.andUp.en": "and up",
  "report.list.andUp": "a vyšší",
  "report.list.severity.en": "Severity:",
  "report.list.severity": "Závažnost:",
  "report.list.reportOnly.en": "only in report",
  "report.list.reportOnly": "pouze v hlášení",
  "report.list.forEditors.en": "For editors level:",
  "report.list.forEditors": "Pro editory úrovně:",
  "report.list.forCountries.en": "For countries:",
  "report.list.forCountries": "Pro země:",
  "report.list.forStates.en": "For states:",
  "report.list.forStates": "Pro státy:",
  "report.list.forCities.en": "For cities:",
  "report.list.forCities": "Pro města:",
  "report.list.params.en": "Params to configure in localization pack:",
  "report.list.params": "Parametry pro konfiguraci lokalizačním balíčku:",
  "report.list.params.set.en": "Current configuration for ${country}:",
  "report.list.params.set": "Aktuální konfigurace pro ${country}:",
  "report.list.enabled.en": "${n} checks are enabled for",
  "report.list.enabled": "${n} kontrol zapnuto pro",
  "report.list.disabled.en": "${n} checks are disabled for",
  "report.list.disabled": "${n} kontrol vypnuto pro",
  "report.list.total.en": "There are ${n} checks available",
  "report.list.total": "Celkem ${n} dostupných kontrol",
  "report.list.title.en": "Complete List of Checks for",
  "report.list.title": "Kompletní seznam kontrol pro",
  "report.list.see.en": "See",
  "report.list.see": "Viz",
  "report.list.checks.en": "Settings->About->Available checks",
  "report.list.checks": "Nastavení->Info->Dostupné kontroly",
  "report.list.fallback.en": "Localization Fallback Rules:",
  "report.list.fallback": "Pravidla lokalizace:",
  "report.and.en": "and",
  "report.and": "a",
  "report.segments.en": "Total number of segments checked:",
  "report.segments": "Celkový počet zkontrolovaných segmentů:",
  "report.customs.en": "Custom checks matched (green/blue):",
  "report.customs": "Uživatelské kontroly (zelená/modrá):",
  "report.reported.en": "Reported",
  "report.reported": "Ohlášeno",
  "report.errors.en": "errors",
  "report.errors": "chyb",
  "report.warnings.en": "warnings",
  "report.warnings": "varování",
  "report.notes.en": "notes",
  "report.notes": "poznámek",
  "report.link.wiki.en": "wiki",
  "report.link.wiki": "wiki",
  "report.link.forum.en": "forum",
  "report.link.forum": "fórum",
  "report.link.other.en": "link",
  "report.link.other": "odkaz",
  "report.contents.en": "Contents:",
  "report.contents": "Obsah:",
  "report.summary.en": "Summary",
  "report.summary": "Shrnutí",
  "report.title.en": "WME Validator Report",
  "report.title": "Hlášení WME Validátoru",
  "report.share.en": "to Share",
  "report.share": "ke sdílení",
  "report.generated.by.en": "generated by",
  "report.generated.by": "vytvořil",
  "report.generated.on.en": "on",
  "report.generated.on": "dne",
  "report.source.en": "Report source:",
  "report.source": "Kontrolovaná oblast:",
  "report.filter.duplicate.en": "duplicate segments",
  "report.filter.duplicate": "duplikované segmenty",
  "report.filter.streets.en": "Streets and Service Roads",
  "report.filter.streets": "ulice a obslužné komunikace",
  "report.filter.other.en": "Other drivable and Non-drivable",
  "report.filter.other": "ostatní sjízdné a nesjízdné",
  "report.filter.noneditable.en": "non-editable segments",
  "report.filter.noneditable": "needitovatelné segmenty",
  "report.filter.notes.en": "notes",
  "report.filter.notes": "poznámky",
  "report.filter.title.en": "Filter:",
  "report.filter.title": "Filtr:",
  "report.filter.excluded.en": "are excluded from this report.",
  "report.filter.excluded": "jsou z tohoto reportu vyloučeny.",
  "report.search.updated.by.en": "updated by",
  "report.search.updated.by": "aktualizoval",
  "report.search.updated.since.en": "updated since",
  "report.search.updated.since": "aktualizováno od",
  "report.search.city.en": "from",
  "report.search.city": "z",
  "report.search.reported.en": "reported as",
  "report.search.reported": "hlášeno jako",
  "report.search.title.en": "Search:",
  "report.search.title": "Hledat:",
  "report.search.only.en": "only segments",
  "report.search.only": "pouze segmenty",
  "report.search.included.en": "are included into the report.",
  "report.search.included": "jsou zařazeny do hlášení.",
  "report.beta.warning.en": "WME Beta Warning!",
  "report.beta.warning": "WME Beta varování!",
  "report.beta.text.en": "This report is generated in beta WME with beta permalinks.",
  "report.beta.text": "Toto hlášení je vytvořeno pomocí WME beta s beta odkazy.",
  "report.beta.share.en": "Please do not share those permalinks!",
  "report.beta.share": "Prosím, nesdílejte tyto permalinky!",
  "report.size.warning.en": "<b>Warning!</b><br>The report is ${n} characters long so <b>it will not fit</b> into a single forum or private message.\n<br>Please add <b>more filters</b> to reduce the size of the report.",
  "report.size.warning": "<b>Varování!</b><br>Hlášení je ${n} znaků dlouhé, takže <b>se nevejde</b> do jedné zprávy na fóru nebo soukromé zprávy (PM).\n<br>Prosíme, přidejte <b>více filtrů</b> k omezení velikosti hlášení.",
  "report.note.limit.en": "* Note: there were too many issues reported, so some of them are not counted in the summary.",
  "report.note.limit": "* Poznámka: je hlášeno příliš mnoho chyb, takže některé nejsou započítány do souhrnu.",
  "report.forum.en": "To motivate further development please leave your comment on the",
  "report.forum": "Chcete-li motivovat další vývojáře, nechte zprávu na",
  "report.forum.link.en": "Waze forum thread.",
  "report.forum.link": "vláknu Waze fóra.",
  "report.thanks.en": "Thank you for using WME Validator!",
  "report.thanks": "Děkujeme, že používáte WME Validátor!",
  "msg.limit.segments.en": "There are too many segments.\n\nClick 'Show report' to review the report, then\n",
  "msg.limit.segments": "Je tady příliš mnoho segmentů.\n\nKlikněte na 'Ukázat hlášení' pro obnovení hlášení, pak\n",
  "msg.limit.segments.continue.en": "click '▶' (Play) to continue.",
  "msg.limit.segments.continue": "klikněte na '▶' (Spustit) pro pokračování.",
  "msg.limit.segments.clear.en": "click '✘' (Clear) to clear the report.",
  "msg.limit.segments.clear": "klikněte na '✘' (Vyčistit) pro vyčištění hlášení.",
  "msg.pan.text.en": "Pan around to validate the map",
  "msg.pan.text": "Pohybujte se nad mapou pro provedení kontroly",
  "msg.zoomout.text.en": "Zoom out to start WME Validator",
  "msg.zoomout.text": "Pro spuštění WME Validátoru oddalte pohled na mapu",
  "msg.click.text.en": "Click '▶' (Play) to validate visible map area",
  "msg.click.text": "Klikněte na '▶' (Spustit) pro kontrolu viditelné oblasti mapy",
  "msg.autopaused.en": "autopaused",
  "msg.autopaused": "automatická pauza",
  "msg.autopaused.text.en": "Auto paused! Click '▶' (Play) to continue.",
  "msg.autopaused.text": "Automaticky pozastaveno! Klikněte na '▶' (Spusit) pro pokračování.",
  "msg.autopaused.tip.en": "WME Validator automatically paused on map drag or window size change",
  "msg.autopaused.tip": "WME Validátor se automaticky pozastaví při posunutí mapy nebo změně velikosti okna",
  "msg.finished.text.en": "Click <b>'Show report'</b> to review map issues",
  "msg.finished.text": "Klikněte na <b>'Ukázat hlášení'</b> pro prohlédnutí chyb mapy",
  "msg.finished.tip.en": "Click '✉' (Share) button to post report on a\nforum or in a private message",
  "msg.finished.tip": "Klikněte na tlačítko '✉' (Sdílet) a pošlete hlášení na a\nforum nebo jako soukromou zprávu",
  "msg.noissues.text.en": "Finished! No issues found!",
  "msg.noissues.text": "Dokončeno! Žádné chyby nenalezeny!",
  "msg.noissues.tip.en": "Try to uncheck some filter options or start WME Validator over another map area!",
  "msg.noissues.tip": "Zkuste zrušit některé filtry nebo spustit WME Validátor nad jinou oblastí mapy!",
  "msg.scanning.text.en": "Scanning! Finishing in ~ ${n} min",
  "msg.scanning.text": "Skenuji! Dokončení za ~ ${n} min",
  "msg.scanning.text.soon.en": "Scanning! Finishing in a minute!",
  "msg.scanning.text.soon": "Skenuji! Dokončení během minuty!",
  "msg.scanning.tip.en": "Click 'Pause' button to pause or '■' (Stop) to stop",
  "msg.scanning.tip": "Klikněte na tlačítko 'Pauza' pro pozastavení nebo '■' (Stop) pro ukončení",
  "msg.starting.text.en": "Starting! Layers are off to scan faster!",
  "msg.starting.text": "Startuji! Pro rychlejší sken jsou vrstvy vypnuty!",
  "msg.starting.tip.en": "Use 'Pause' button to pause or '■' button to stop",
  "msg.starting.tip": "Použijte tlačítko 'Pauza' pro pozastavení nebo '■' pro ukončení",
  "msg.paused.text.en": "On pause! Click '▶' (Play) button to continue.",
  "msg.paused.text": "Pozastaveno! Klikněte na tlačítko '▶' (Spustit) pro pokračování.",
  "msg.paused.tip.en": "To view the report click 'Show report' button (if available)",
  "msg.paused.tip": "Pro prohlédnutí hlášení klikněte na tlačítko 'Ukázat hlášení' (pokud je dostupné)",
  "msg.continuing.text.en": "Continuing!",
  "msg.continuing.text": "Pokračuji!",
  "msg.continuing.tip.en": "WME Validator will continue from the location it was paused",
  "msg.continuing.tip": "WME Validátor bude pokračovat od místa, kde byl přerušen",
  "msg.settings.text.en": "Click <b>'Back'</b> to return to main view",
  "msg.settings.text": "Klikněte na tlačítko <b>'Zpět'</b> pro návrat na hlavní okno",
  "msg.settings.tip.en": "Click 'Reset defaults' button to reset all settings in one click!",
  "msg.settings.tip": "Pro navrácení voleb na původní nastavení klikněte na tlačítko 'Obnov výchozí'!",
  "msg.reset.text.en": "All filter options and settings have been reset to their defaults",
  "msg.reset.text": "Nastavení filtrů a voleb bude vráceno na původní nastavení",
  "msg.reset.tip.en": "Click 'Back' button to return to main view",
  "msg.reset.tip": "Klikněte na tlačítko 'Zpět' pro návrat na hlavní okno",
  "msg.textarea.pack.en": "This is a Greasemonkey/Tampermonkey script. You can copy and paste the text below into a <b>new .user.js file</b><br>or <b>paste it directly</b> into the Greasemonkey/Tampermonkey",
  "msg.textarea.pack": "Toto je Greasemonkey/Tampermonkey skript. Text níže můžete  zkopírovat a vložit do <b>nového .user.js souboru</b><br>nebo ho <b>vložit přímo</b> do Greasemonkey/Tampermonkey",
  "msg.textarea.en": "Please copy the text below and then paste it into your forum post or private message",
  "msg.textarea": "Prosím, zkopírujte text níže a vložte ho do příspěvku na fóru nebo do soukromé zprávy",
  "noaccess.text.en": "<b>Sorry,</b><br>You cannot use WME Validator over here.<br>Please check <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>the forum thread</a><br>for more information.",
  "noaccess.text": "<b>Omlouváme se,</b><br>Tady nemůžete použít WME Validátor.<br>Přečtěte si <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>vlákno na fóru</a><br>pro více informací.",
  "noaccess.tip.en": "Please check the forum thread for more information!",
  "noaccess.tip": "Prosím, přečtěte si vlákno ve fóru pro více informací!",
  "tab.switch.tip.on.en": "Click to switch highlighting on (Alt+V)",
  "tab.switch.tip.on": "Zapnout zvýraznění (Alt+V)",
  "tab.switch.tip.off.en": "Click to switch highlighting off (Alt+V)",
  "tab.switch.tip.off": "Vypnout zvýraznění (Alt+V)",
  "tab.filter.text.en": "filter",
  "tab.filter.text": "filtr",
  "tab.filter.tip.en": "Options to filter the report and highlighted segments",
  "tab.filter.tip": "Možnosti filtrování zpráv a zvýrazněných segmentů",
  "tab.search.text.en": "search",
  "tab.search.text": "hledat",
  "tab.search.tip.en": "Advanced filter options to include only specific segments",
  "tab.search.tip": "Pokročilé možnosti filtrování zahrnují pouze určité segmenty",
  "tab.help.text.en": "help",
  "tab.help.text": "pomoc",
  "tab.help.tip.en": "Need help?",
  "tab.help.tip": "Potřebujete pomoc?",
  "filter.noneditables.text.en": "Exclude <b>non-editable</b> segments",
  "filter.noneditables.text": "Vyloučit  <b>needitovatelné</b> segmenty",
  "filter.noneditables.tip.en": "Do not report locked segments or\nsegments outside of your editable areas",
  "filter.noneditables.tip": "Nehlásit zamčené segmenty nebo\nsegmenty mimo vaši editační oblast",
  "filter.duplicates.text.en": "Exclude <b>duplicate</b> segments",
  "filter.duplicates.text": "Vyloučit <b>duplikované</b> segmenty",
  "filter.duplicates.tip.en": "Do not show the same segment in different\nparts of report\n* Note: this option DOES NOT affect highlighting",
  "filter.duplicates.tip": "Nezobrazovat stejné segmenty v různých\nčástech hlášení\n* Poznámka: tato volba NEOVLIVNÍ zvýraznění",
  "filter.streets.text.en": "Exclude <b>Streets and Service Roads</b>",
  "filter.streets.text": "Vyloučit <b>ulice a obslužné komunikace</b>",
  "filter.streets.tip.en": "Do not report Streets and Service Roads",
  "filter.streets.tip": "Nehlásit ulice a obslužné komunikace",
  "filter.other.text.en": "Exclude <b>Other drivable and Non-drivable</b>",
  "filter.other.text": "Vyloučit <b>další sjízdné a nesjízdné</b>",
  "filter.other.tip.en": "Do not report Dirt, Parking Lot, Private Roads\nand non-drivable segments",
  "filter.other.tip": "Nehlásit lesní a polní cesty, uličky na parkovišti,\nsoukromé cesty a nesjízdné segmenty",
  "filter.notes.text.en": "Exclude <b>notes</b>",
  "filter.notes.text": "Vyloučit <b>poznámky</b>",
  "filter.notes.tip.en": "Report only warnings and errors",
  "filter.notes.tip": "Hlásit pouze varování a chyby",
  "search.youredits.text.en": "Include <b>only your edits</b>",
  "search.youredits.text": "Zahrnout <b>pouze vaše editace</b>",
  "search.youredits.tip.en": "Include only segments edited by you",
  "search.youredits.tip": "Zahrnout pouze segmenty editované vámi",
  "search.updatedby.text.en": "<b>Updated by:</b>",
  "search.updatedby.text": "<b>Aktualizoval:</b>",
  "search.updatedby.tip.en": "Include only segments updated by the specified editor\nThis field supports:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Note: you may use 'me' to match yourself",
  "search.updatedby.tip": "Zahrnout pouze segmenty aktualizované zadaným editorem\nToto pole podporuje:\n - seznamy: me, otherEditor\n - zástupné znaky: world*\n - negace: !me, *\n* Poznámka: můžete použít 'me', abyste zkontrolovali své edity",
  "search.updatedby.example.en": "Example: me",
  "search.updatedby.example": "Příklad: me",
  "search.updatedsince.text.en": "<b>Updated since:</b>",
  "search.updatedsince.text": "<b>Aktualizováno od:</b>",
  "search.updatedsince.tip.en": "Include only segments edited since the date specified\nFirefox date format: YYYY-MM-DD",
  "search.updatedsince.tip": "Zahrnout pouze segmenty upravené od určitého data",
  "search.updatedsince.example.en": "YYYY-MM-DD",
  "search.updatedsince.example": "RRRR-MM-DD",
  "search.city.text.en": "<b>City name:</b>",
  "search.city.text": "<b>Název města:</b>",
  "search.city.tip.en": "Include only segments with specified city name\nThis field supports:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
  "search.city.tip": "Zahrnout pouze segmenty s určitým názvem města\nToto pole podporuje:\n - seznamy: Paris, Meudon\n - zástupné znaky: Greater * Area\n - negace: !Paris, *",
  "search.city.example.en": "Example: !Paris, *",
  "search.city.example": "Příklad: !Paris, *",
  "search.checks.text.en": "<b>Reported as:</b>",
  "search.checks.text": "<b>Hlášeno jako:</b>",
  "search.checks.tip.en": "Include only segments reported as specified\nThis field matches:\n - severities: errors\n - check names: New road\n - check IDs: 200\nThis field supports:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
  "search.checks.tip": "Zahrnout pouze určité segmenty\nToto pole porovnává:\n - závažnost: chyby\n - kontrolu jména: Nová cesta\n - kontrolu ID: 200\nToto pole podporuje:\n - seznamy: 36, 37\n - zástupné znaky: *roundabout*\n - negace: !unconfirmed*, *",
  "search.checks.example.en": "Example: reverse*",
  "search.checks.example": "Příklad: reverse*",
  "help.text.en": "<b>Help Topics:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Ask your question on the forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">How to adjust Validator for your country</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">About the \"Might be Incorrect City Name\"</a>",
  "help.text": "<b>Nápověda:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Polož otázku na fóru</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Jak vyladit Validátor pro tvou zemi</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Detaily k chybě <br>\"Pravděpodobně nesprávný název města\"</a>",
  "help.tip.en": "Open in a new browser tab",
  "help.tip": "Otevřít v nové záložce",
  "button.scan.tip.en": "Start scanning current map area\n* Note: this might take few minutes",
  "button.scan.tip": "Začít skenovat aktuální oblast mapy\n* Poznámka: může to zabrat pár minut",
  "button.scan.tip.NA.en": "Zoom out to start scanning current map area",
  "button.scan.tip.NA": "Pro spuštění kontroly oblasti oddalte mapu",
  "button.pause.tip.en": "Pause scanning",
  "button.pause.tip": "Pozastavit skenování",
  "button.continue.tip.en": "Continue scanning the map area",
  "button.continue.tip": "Pokračovat ve skenování oblasti mapy",
  "button.stop.tip.en": "Stop scanning and return to the start position",
  "button.stop.tip": "Ukončit skenování a vrátit se na výchozí pozici",
  "button.clear.tip.en": "Clear report and segment cache",
  "button.clear.tip": "Vyčistit vyrovnávací paměť hlášení a segmentů",
  "button.clear.tip.red.en": "There are too many reported segments:\n 1. Click 'Show report' to generate the report.\n 2. Click this button to clear the report and start over.",
  "button.clear.tip.red": "Je tady příliš mnoho nahlášených segmentů:\n 1. Klikněte na 'Ukázat hlášení' pro vytvoření hlášení.\n 2. Klikněte na toto tlačítko, abyste vyčistili hlášení a začali znovu.",
  "button.report.text.en": "Show report",
  "button.report.text": "Ukázat hlášení",
  "button.report.tip.en": "Apply the filter and generate HTML report in a new tab",
  "button.report.tip": "Použít filtr a generovat HTML hlášení v nové záložce",
  "button.BBreport.tip.en": "Share the report on Waze forum or in a private message",
  "button.BBreport.tip": "Sdílet zprávu na Waze fóru nebo v soukromé zprávě",
  "button.settings.tip.en": "Configure settings",
  "button.settings.tip": "Konfigurace nastavení",
  "tab.custom.text.en": "custom",
  "tab.custom.text": "vlastní",
  "tab.custom.tip.en": "User-defined custom checks settings",
  "tab.custom.tip": "Uživatelem definované nastavení kontroly",
  "tab.settings.text.en": "Settings",
  "tab.settings.text": "Nastavení",
  "tab.scanner.text.en": "scanner",
  "tab.scanner.text": "skener",
  "tab.scanner.tip.en": "Map scanner settings",
  "tab.scanner.tip": "Nastavení skeneru mapy",
  "tab.about.text.en": "about</span>",
  "tab.about.text": "Info</span>",
  "tab.about.tip.en": "About WME Validator",
  "tab.about.tip": "O WME Validátoru",
  "scanner.sounds.text.en": "Enable sounds",
  "scanner.sounds.text": "Zapnout zvuk",
  "scanner.sounds.tip.en": "Bleeps and the bloops while scanning",
  "scanner.sounds.tip": "Pípání při skenování",
  "scanner.sounds.NA.en": "Your browser does not support AudioContext",
  "scanner.sounds.NA": "Váš prohlížeč nepodporuje AudioContext",
  "scanner.highlight.text.en": "Highlight issues on the map",
  "scanner.highlight.text": "Zvýraznit problémy na mapě",
  "scanner.highlight.tip.en": "Highlight reported issues on the map",
  "scanner.highlight.tip": "Zvýrazní nahlášené chyby na mapě",
  "scanner.slow.text.en": "Enable \"slow\" checks",
  "scanner.slow.text": "Zapnout \"pomalou\" kontrolu",
  "scanner.slow.tip.en": "Enables deep map analysis\n* Note: this option might slow down the scanning process",
  "scanner.slow.tip": "Zapne hloubkovou analýzu\n* Poznámka: tato volba může zpomalit skenovací proces",
  "scanner.ext.text.en": "Report external highlights",
  "scanner.ext.text": "Hlásit externí zvýraznění",
  "scanner.ext.tip.en": "Report segments highlighted by WME Toolbox or WME Color Highlights",
  "scanner.ext.tip": "Hlásit segmenty zvýrazněné skripty WME Toolbox nebo WME Color Highlights",
  "advanced.twoway.text.en": "WME: Two-way segments by default",
  "advanced.twoway.text": "WME: Segmenty jsou obousměrné",
  "advanced.twoway.tip.en": "Newly created streets in WME are bidirectional by default",
  "advanced.twoway.tip": "Nově vytvořené segmenty budou obousměrné jako výchozí",
  "custom.template.text.en": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Custom template</a>",
  "custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Vlastní šablona</a>",
  "custom.template.tip.en": "User-defined custom check expandable template.\n\nYou may use the following expandable variables:\nAddress:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nSegment properties:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nHelpers:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nConnectivity:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.tip": "Vlastní uživatelsky rozšířitelná šablona kontrol.\n\nMůžete použít následující rozšiřující proměnné:\nAddresa:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nParametry segmentů:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nPomocníci:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nConnectivity:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.example.en": "Example: ${street}",
  "custom.template.example": "Příklad: ${street}",
  "custom.regexp.text.en": "Custom <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
  "custom.regexp.text": "Vlastní <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
  "custom.regexp.tip.en": "User-defined custom check regular expression to match the template.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
  "custom.regexp.tip": "Uživatelsky definované výrazy pro kontrolu.\n\nShoda velkých/malých písmen: /regexp/i\nNegace (neshoduje se): !/regexp/\nVýpis ladicích informací na konzoli: D/regexp/",
  "custom.regexp.example.en": "Example: !/.+/",
  "custom.regexp.example": "Příklad: !/.+/",
  "about.tip.en": "Open link in a new tab",
  "about.tip": "Otevřít odkaz v nové záložce",
  "button.reset.text.en": "Reset defaults",
  "button.reset.text": "Nastavit výchozí",
  "button.reset.tip.en": "Revert filter options and settings to their defaults",
  "button.reset.tip": "Vrátit filtry nastavení a voleb na výchozí nastavení",
  "button.list.text.en": "Available checks...",
  "button.list.text": "Dostupné kontroly...",
  "button.list.tip.en": "Show a list of checks available in WME Validator",
  "button.list.tip": "Ukázat seznam kontrol dostupných ve WME Validátoru",
  "button.wizard.tip.en": "Create localization package",
  "button.wizard.tip": "Vytvořit lokalizační balíček",
  "button.back.text.en": "Back",
  "button.back.text": "Zpět",
  "button.back.tip.en": "Close settings and return to main view",
  "button.back.tip": "Zavře nastavení a vrátí se na hlavní okno",
  "1.title.en": "WME Toolbox: Roundabout which may cause issues",
  "1.title": "WME Toolbox: Kruhový objezd, který může způsobit problémy",
  "1.problem.en": "Junction IDs of the roundabout segments are not consecutive",
  "1.problem": "ID segmentů kruhového objezdu nejsou po sobě jdoucí",
  "1.solution.en": "Redo the roundabout",
  "1.solution": "Udělejte kruhový objezd znovu",
  "2.title.en": "WME Toolbox: Simple segment",
  "2.title": "WME Toolbox: Jednoduchý segment",
  "2.problem.en": "The segment has unneeded geometry nodes",
  "2.problem": "Segment má nepotřebné geometrické body",
  "2.solution.en": "Simplify segment geometry by hovering mouse pointer and pressing \"d\" key",
  "2.solution": "Najeďte myší nad nepotřebný bod a stiskem klávesy \"d\" ho smažte",
  "3.title.en": "WME Toolbox: Lvl 2 lock",
  "3.title": "WME Toolbox: Uzamčeno na úroveň 2",
  "3.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "3.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "4.title.en": "WME Toolbox: Lvl 3 lock",
  "4.title": "WME Toolbox: Uzamčeno na úroveň 3",
  "4.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "4.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "5.title.en": "WME Toolbox: Lvl 4 lock",
  "5.title": "WME Toolbox: Uzamčeno na úroveň 4",
  "5.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "5.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "6.title.en": "WME Toolbox: Lvl 5 lock",
  "6.title": "WME Toolbox: Uzamčeno na úroveň 5",
  "6.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "6.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "7.title.en": "WME Toolbox: Lvl 6 lock",
  "7.title": "WME Toolbox: Uzamčeno na úroveň 6",
  "7.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "7.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "8.title.en": "WME Toolbox: House numbers",
  "8.title": "WME Toolbox: Domovní čísla",
  "8.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "8.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "9.title.en": "WME Toolbox: Segment with time restrictions",
  "9.title": "WME Toolbox: Segment s časovým omezením",
  "9.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "9.problem": "Segment zvýraznil WME Toolbox. Není to problém",
  "13.title.en": "WME Color Highlights: Editor lock",
  "13.title": "WME Color Highlights: Uzamčený segment",
  "13.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "13.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "14.title.en": "WME Color Highlights: Toll road / One way road",
  "14.title": "WME Color Highlights: Zpoplatněno / Jednosměrka",
  "14.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "14.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "15.title.en": "WME Color Highlights: Recently edited",
  "15.title": "WME Color Highlights: Nedávno editováno",
  "15.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "15.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "16.title.en": "WME Color Highlights: Road rank",
  "16.title": "WME Color Highlights: Kategorie silnic",
  "16.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "16.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "17.title.en": "WME Color Highlights: No city",
  "17.title": "WME Color Highlights: Žádné město",
  "17.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "17.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "18.title.en": "WME Color Highlights: Time restriction / Highlighted road type",
  "18.title": "WME Color Highlights: Časové omezení / Zvýrazněný typ cesty",
  "18.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "18.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "19.title.en": "WME Color Highlights: No name",
  "19.title": "WME Color Highlights: Bez názvu",
  "19.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "19.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "20.title.en": "WME Color Highlights: Filter by city",
  "20.title": "WME Color Highlights: Filtrováno podle města",
  "20.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "20.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "21.title.en": "WME Color Highlights: Filter by city (alt. city)",
  "21.title": "WME Color Highlights: Filtrováno podle města (alt. město)",
  "21.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "21.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "22.title.en": "WME Color Highlights: Filter by editor",
  "22.title": "WME Color Highlights: Filtrováno podle editora",
  "22.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "22.problem": "Segment zvýraznil WME Color Highlights. Není to problém",
  "23.title.en": "Unconfirmed road",
  "23.title": "Nepotvrzená cesta",
  "23.problem.en": "Each segment must minimally have the Country and State information",
  "23.problem": "Každý segment musí mít minimálně informace o zemi",
  "23.solution.en": "Confirm the road by updating its details",
  "23.solution": "Potvrď cestu doplněním informací",
  "24.title.en": "Might be incorrect city name (only available in the report)",
  "24.title": "Pravděpodobně špatný název města (dostupné pouze v hlášení)",
  "24.problem.en": "The segment might have incorrect city name",
  "24.problem": "Segment může mít špatný název města",
  "24.solution.en": "Consider suggested city name and use this form to rename the city",
  "24.solution": "Zvažte navržený název města a použijte tento formulář k přejmenování města",
  "25.title.en": "Unknown direction of drivable road",
  "25.title": "Neznámý směr jízdy na sjízdné cestě",
  "25.problem.en": "'Unknown' road direction will not prevent routing on the road",
  "25.problem": "Směr jízdy 'Neznámý' nezabrání použití této cesty při navigaci",
  "25.solution.en": "Set the road direction",
  "25.solution": "Nastavte směr jízdy",
  "27.enabled": true,
  "27.title.en": "City name on Railroad",
  "27.title": "Železnice má vyplněno jméno města",
  "27.problem.en": "City name on the Railroad may cause a city smudge",
  "27.problem": "Název města u železnice může způsobit nechtěné zvětšení plochy města na mapě",
  "27.solution.en": "In the address properties check the 'None' box next to the city name and then click 'Apply'",
  "27.solution": "V nastavení adresy zaškrtněte 'Nic' vedle jména města a klikněte na 'Potvrdit'",
  "28.title.en": "Street name on two-way Ramp",
  "28.title": "Název silnice na obousměrné rampě",
  "28.problem.en": "If Ramp is unnamed, the name of a subsequent road will propagate backwards",
  "28.problem": "Pokud je rampa nepojmenovaná, při navigaci se zobrazuje název navazující komunikace",
  "28.solution.en": "In the address properties check the 'None' box next to the street name and then click 'Apply'",
  "28.solution": "V nastavení adresy zaškrtněte 'Nic' vedle názvu silnice a klikněte na 'Potvrdit'",
  "29.title.en": "Street name on roundabout",
  "29.title": "Název ulice na kruhovém objezdu",
  "29.problem.en": "In Waze, we do not name roundabout segments",
  "29.problem": "Ve Waze segmenty kruhových objezdů nemají název ulice",
  "29.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout",
  "29.solution": "V nastavení adresy zaškrtněte 'Nic' vedle názvu silnice a klikněte na 'Potvrdit' a poté vnitřní plochu kruhového objezdu vyplňte Místem kategorie 'Křižovatka' se jménem kruhového objezdu",
  "34.title.en": "Empty alternate street",
  "34.title": "Prázdný 'Další název' cesty",
  "34.problem.en": "Alternate street name is empty",
  "34.problem": "'Další název' cesty je prázdný",
  "34.solution.en": "Remove empty alternate street name",
  "34.solution": "Odstraň prázdný 'Další název' cesty",
  "35.title.en": "Unterminated drivable road",
  "35.title": "Neukončená sjízdná cesta",
  "35.problem.en": "Waze will not route from the unterminated segment",
  "35.problem": "Waze nebude navigovat z neukončeného segmentu",
  "35.solution.en": "Move the segment a bit so the terminating node will be added automatically",
  "35.solution": "Posuňte malinko segment tak, aby se ukončení segmentu automaticky přidalo",
  "36.title.en": "Node A: Unneeded (slow)",
  "36.title": "Nepotřebný uzel A",
  "36.problem.en": "Adjacent segments at node A are identical",
  "36.problem": "Segmenty spojené uzlem A mají shodné vlastnosti",
  "36.solution.en": "Select node A and press Delete key to join the segments",
  "36.solution": "Vyberte uzel A a stiskem klávesy Delete spojte segmenty",
  "37.title.en": "Node B: Unneeded (slow)",
  "37.title": "Nepotřebný uzel B",
  "37.problem.en": "Adjacent segments at node B are identical",
  "37.problem": "Segmenty spojené uzlem B mají shodné vlastnosti",
  "37.solution.en": "Select node B and press Delete key to join the segments",
  "37.solution": "Vyberte uzel B a stiskem klávesy Delete spojte segmenty",
  "38.title.en": "Expired segment restriction (slow)",
  "38.title": "Omezení segmentu vypršelo",
  "38.problem.en": "The segment has an expired restriction",
  "38.problem": "Segment má omezení, jehož platnost již skončila",
  "38.solution.en": "Click 'Edit restrictions' and delete the expired restriction",
  "38.solution": "Klikněte na 'Upravit omezení' a zrušte neplatné omezení",
  "39.title.en": "Expired turn restriction (slow)",
  "39.title": "Omezení odbočení vypršelo",
  "39.problem.en": "The segment has a turn with an expired restriction",
  "39.problem": "Odbočení ze segmentu má omezení, jehož platnost již skončila",
  "39.solution.en": "Click clock icon next to the yellow arrow and delete the expired restriction",
  "39.solution": "Klikněte na ikonu hodin vedle žluté šipky a zrušte neplatné omezení",
  "41.title.en": "Node A: Reverse connectivity of drivable road",
  "41.title": "Uzel A: Opačné propojení sjízdných segmentů",
  "41.problem.en": "There is a turn which goes against the directionality of the segment at node A",
  "41.problem": "Je nastaveno odbočení, který vede proti směru jízdy segmentu v uzlu A",
  "41.solution.en": "Make the segment 'Two-way', restrict all the turns at node A and then make the segment 'One way (A→B)' again",
  "41.solution": "Nastavte směr 'Obousměrný', zakažte všechna odbočení v uzlu A a pak znovu nastavte směr 'Jednosměrný (A→B)'",
  "42.title.en": "Node B: Reverse connectivity of drivable road",
  "42.title": "Uzel B: Opačné propojení sjízdných segmentů",
  "42.problem.en": "There is a turn which goes against the directionality of the segment at node B",
  "42.problem": "Je nastaveno odbočení, který vede proti směru jízdy segmentu v uzlu B",
  "42.solution.en": "Make the segment 'Two-way', restrict all the turns at node B and then make the segment 'One way (B→A)' again",
  "42.solution": "Nastavte směr 'Obousměrný', zakažte všechna odbočení v uzlu B a pak znovu nastavte směr 'Jednosměrný (B→A)'",
  "43.title.en": "Self connectivity",
  "43.title": "Kruhové propojení",
  "43.problem.en": "The segment is connected back to itself",
  "43.problem": "Segment je připojen sám na sebe a tvoří smyčku",
  "43.solution.en": "Split the segment into THREE pieces",
  "43.solution": "Rozdělte segment na TŘI části",
  "44.title.en": "No outward connectivity",
  "44.title": "Žádný směr výjezdu",
  "44.problem.en": "The drivable segment has no single outward turn enabled",
  "44.problem": "Sjízdný segment nelze opustit žádným směrem",
  "44.solution.en": "Enable at least one outward turn from the segment",
  "44.solution": "Povolte alespoň jedno odbočení ze segmentu ven",
  "45.title.en": "No inward connectivity",
  "45.title": "Žádný směr vjezdu",
  "45.problem.en": "The drivable non-private segment has no single inward turn enabled",
  "45.problem": "Na sjízdný segment nelze přijet z žádného směru",
  "45.solution.en": "Select an adjacent segment and enable at least one turn to the segment",
  "45.solution": "Vyberte sousední segment a povolte alespoň jedno odbočení do segmentu",
  "46.title.en": "Node A: No inward connectivity of drivable road (slow)",
  "46.title": "Uzel A: Žádný směr vjezdu",
  "46.problem.en": "The drivable non-private segment has no single inward turn enabled at node A",
  "46.problem": "Na sjízdný segment nelze v uzlu A najet ze žádného směru",
  "46.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node A",
  "46.solution": "Vyberte sousední segment a povolte alespoň jedno odbočení do segmentu v uzlu A",
  "47.title.en": "Node B: No inward connectivity of drivable road (slow)",
  "47.title": "Uzel B: Žádný směr vjezdu",
  "47.problem.en": "The drivable non-private segment has no single inward turn enabled at node B",
  "47.problem": "Na sjízdný segment nelze v uzlu B najet ze žádného směru",
  "47.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node B",
  "47.solution": "Vyberte sousední segment a povolte alespoň jedno odbočení do segmentu v uzlu B",
  "48.title.en": "Two-way drivable roundabout segment",
  "48.title": "Obousměrný segment v kruhovém objezdu",
  "48.problem.en": "The drivable roundabout segment is bidirectional",
  "48.problem": "Sjízdný segment kruhového objezdu je obousměrný",
  "48.solution.en": "Redo the roundabout",
  "48.solution": "Vytvořte kruhový objezd znovu",
  "50.title.en": "No connectivity on roundabout (slow)",
  "50.title": "Zakázaný směr v kruhovém objezdu",
  "50.problem.en": "The drivable roundabout segment has no connectivity with adjacent roundabout segment",
  "50.problem": "Sjízdný segment kruhového objezdu nemá povolenou jízdu na sousedící segment kruhového objezdu",
  "50.solution.en": "Enable a turn to the adjacent segment or redo the roundabout",
  "50.solution": "Povolte odbočení na sousední segment nebo vytvořte kruhový objezd znovu",
  "52.enabled": true,
  "52.title.en": "Too long street name",
  "52.title": "Příliš dlouhý název ulice",
  "52.problem.en": "The name of the drivable segment is more than ${n} letters long and it is not a Ramp",
  "52.problem": "Sjízdný segment má příliš dlouhý název, více než ${n} znaků a není to rampa",
  "52.solution.en": "Consider an abbreviation for the street name",
  "52.solution": "Zvažte zkrácení názvu ulice",
  "73.enabled": true,
  "73.title.en": "Too short street name",
  "73.title": "Příliš krátký název ulice",
  "73.problem.en": "The street name is less than ${n} letters long and it is not a highway",
  "73.problem": "Název ulice je kratší než ${n} znaků a není to dálnice",
  "73.solution.en": "Correct the street name",
  "73.solution": "Opravte název ulice",
  "77.enabled": true,
  "77.title.en": "Dead-end U-turn",
  "77.title": "Otočení ve slepé ulici",
  "77.problem.en": "The drivable dead-end road has a U-turn enabled",
  "77.problem": "Sjízdná slepá ulice má povoleno otočení",
  "77.solution.en": "Disable U-turn",
  "77.solution": "Zakažte otočení",
  "78.title.en": "Same endpoints drivable segments (slow)",
  "78.title": "Stejné koncové body sjízdných segmentů",
  "78.problem.en": "Two drivable segments share the same two endpoints",
  "78.problem": "Dva sjízdné segmenty sdílejí oba koncové body a tvoří smyčku",
  "78.solution.en": "Split the segment. You might also remove one of the segments if they are identical",
  "78.solution": "Rozdělte jeden ze segmentů. Případně můžete jeden segment úplně odstranit, pokud jsou shodné",
  "87.title.en": "Node A: Multiple outgoing segments at roundabout",
  "87.title": "Uzel A: Více odchozích segmentů v kruhovém objezdu",
  "87.problem.en": "The drivable roundabout node A has more than one outgoing segment connected",
  "87.problem": "Sjízdný kruhový objezd má v uzlu A připojen více než jeden odchozí segment",
  "87.solution.en": "Redo the roundabout",
  "87.solution": "Vytvořte kruhový objezd znovu",
  "90.enabled": true,
  "90.title.en": "Two-way Freeway segment",
  "90.title": "Obousměrný segment dálnice",
  "90.problem.en": "Most of the Freeways are split into two one-way roads, so this two-way segment might be a mistake",
  "90.problem": "Většina dálnic je rozdělena do dvou jednosměrných komunikací, takže obousměrné segmenty dálnice mohou být chybou",
  "90.solution.en": "Check Freeway direction",
  "90.solution": "Zkontrolujte směr jízdy na dálnici",
  "99.title.en": "U-turn at roundabout entrance (slow)",
  "99.title": "Otočení na vjezdu do kruhového objezdu",
  "99.problem.en": "The roundabout entrance segment has a U-turn enabled",
  "99.problem": "Segment vjíždějící na kruhový objezd má povoleno otočení",
  "99.solution.en": "Disable U-turn",
  "99.solution": "Zakažte otočení",
  "101.title.en": "Closed road (only available in the report)",
  "101.title": "Uzavřená cesta (dostupné pouze v hlášení)",
  "101.problem.en": "The segment is marked as closed",
  "101.problem": "Segment je označen jako uzavřený",
  "101.solution.en": "If the construction is done, restore the segment connectivity and remove the suffix",
  "101.solution": "Pokud stavba skončila, obnovte připojení segmentu a odstraňte označení stavby",
  "102.title.en": "Node A: No outward connectivity of drivable road (slow)",
  "102.title": "Uzel A: Žádný směr výjezdu",
  "102.problem.en": "The drivable segment has no single outward turn enabled at node A",
  "102.problem": "Sjízdný segment nelze v uzlu A opustit žádným směrem",
  "102.solution.en": "Enable at least one outward turn from the segment at node A",
  "102.solution": "Povolte v uzlu A alespoň jedno odbočení ze segmentu ven",
  "103.title.en": "Node B: No outward connectivity of drivable road (slow)",
  "103.title": "Uzel B: Žádný směr výjezdu",
  "103.problem.en": "The drivable segment has no single outward turn enabled at node B",
  "103.problem": "Sjízdný segment nelze v uzlu B opustit žádným směrem",
  "103.solution.en": "Enable at least one outward turn from the segment at node B",
  "103.solution": "Povolte v uzlu B alespoň jedno odbočení ze segmentu ven",
  "104.enabled": true,
  "104.title.en": "Railroad used for comments",
  "104.title": "Železnice použita jako komentář",
  "104.problem.en": "The Railroad segment is probably used as a map comment",
  "104.problem": "Segment železnice byl pravděpodobně použit v mapě jako komentář",
  "104.solution.en": "Remove the comment as Railroads will be added to the client display",
  "104.solution": "Odstraňte 'železniční komentář', protože bude vidět v klientovi",
  "105.enabled": true,
  "105.title.en": "Walking Trail instead of a Railroad",
  "105.title": "Stezka pro chodce namísto železnice",
  "105.problem.en": "The Walking Trail segment with elevation -5 is probably used instead of a Railroad",
  "105.problem": "Segment 'Stezka pro chodce' s výškou -5 je pravděpodobně použit namísto železnice",
  "105.solution.en": "Change road type to Railroad as Railroads will be added to the client display",
  "105.solution": "Změňte typ cesty na 'Železnice' a upravte výšku",
  "107.title.en": "Node A: No connection (slow)",
  "107.title": "Uzel A: Nespojené cesty",
  "107.problem.en": "The node A of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "107.problem": "Uzel A sjízdného segmentu je méně než 5 m od jiné sjízdného segmentu, ale není spojen křižovatkou",
  "107.solution.en": "Drag the node A to the nearby segment so that it touches or move it a bit further away",
  "107.solution": "Přetáhněte uzel A na nejbližší segment tak, aby se dotýkaly nebo je posuňte kousek dále od sebe",
  "108.title.en": "Node B: No connection (slow)",
  "108.title": "Uzel B: Nespojené cesty",
  "108.problem.en": "The node B of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "108.problem": "Uzel B sjízdného segmentu je méně než 5 m od jiné sjízdného segmentu, ale není spojen křižovatkou",
  "108.solution.en": "Drag the node B to the nearby segment so that it touches or move it a bit further away",
  "108.solution": "Přetáhněte uzel B na nejbližší segment tak, aby se dotýkaly nebo je posuňte kousek dále od sebe",
  "109.title.en": "Too short segment",
  "109.title": "Příliš krátký segment",
  "109.problem.en": "The drivable non-terminal segment is less than ${n}m long so it is hard to see it on the map and it can cause routing problems",
  "109.problem": "Sjízdný segment je kratší než ${n}m, takže je těžké ho vidět v mapě a může způsobit problémy v navigaci",
  "109.solution.en": "Increase the length, or remove the segment, or join it with one of the adjacent segments",
  "109.solution": "Prodlužte nebo odstraňte segment nebo ho připojte k jednomu ze sousedních segmentů",
  "112.title.en": "Too long Ramp name",
  "112.title": "Příliš dlouhý název rampy",
  "112.problem.en": "The Ramp name is more than ${n} letters long",
  "112.problem": "Název rampy je delší než ${n} znaků",
  "112.solution.en": "Shorten the Ramp name",
  "112.solution": "Zkraťte název rampy",
  "114.enabled": false,
  "114.title.en": "Node A: Non-drivable connected to drivable (slow)",
  "114.title": "Uzel A: Nesjízdný segment připojen ke sjízdnému",
  "114.problem.en": "The non-drivable segment makes a junction with a drivable at node A",
  "114.problem": "Nesjízdný segment tvoří křižovatku se sjízdným segmentem v uzlu A",
  "114.solution.en": "Disconnect node A from all of the drivable segments",
  "114.solution": "Odpojte uzel A od všech sjízdných segmentů",
  "115.enabled": false,
  "115.title.en": "Node B: Non-drivable connected to drivable (slow)",
  "115.title": "Uzel B: Nesjízdný segment připojen ke sjízdnému",
  "115.problem.en": "The non-drivable segment makes a junction with a drivable at node B",
  "115.problem": "Nesjízdný segment tvoří křižovatku se sjízdným segmentem v uzlu B",
  "115.solution.en": "Disconnect node B from all of the drivable segments",
  "115.solution": "Odpojte uzel B od všech sjízdných segmentů",
  "116.title.en": "Out of range elevation",
  "116.title": "Výška je mimo rozsah",
  "116.problem.en": "The segment elevation is out of range",
  "116.problem": "Výška segmentu je mimo rozsah",
  "116.solution.en": "Correct the elevation",
  "116.solution": "Opravte výšku",
  "117.title.en": "Obsolete CONST ZN marker",
  "117.title": "Zastaralé označení CONST ZN",
  "117.problem.en": "The segment is marked with obsolete CONST ZN suffix",
  "117.problem": "Segment je označen dříve používaným způsobem vyznačení stavby",
  "117.solution.en": "Change CONST ZN to (closed)",
  "117.solution": "Změňte CONST ZN na (uzavřeno)",
  "118.title.en": "Node A: Overlapping segments (slow)",
  "118.title": "Uzel A: Překrývající se segmenty",
  "118.problem.en": "The segment is overlapping with the adjacent segment at node A",
  "118.problem": "Segment se v uzlu A překrývá s jiným segmentem",
  "118.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node A",
  "118.solution": "Vytvořte mezi segmenty úhel nejméně 2° nebo smažte nepotřebné body geometrie nebo smažte duplikovaný segment v uzlu A",
  "119.title.en": "Node B: Overlapping segments (slow)",
  "119.title": "Uzel B: Překrývající se segmenty",
  "119.problem.en": "The segment is overlapping with the adjacent segment at node B",
  "119.problem": "Segment se v uzlu B překrývá s jiným segmentem",
  "119.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node B",
  "119.solution": "Vytvořte mezi segmenty úhel nejméně 2° nebo smažte nepotřebné body geometrie nebo smažte duplikovaný segment v uzlu B",
  "120.title.en": "Node A: Too sharp turn (slow)",
  "120.title": "Uzel A: Příliš ostrý úhel",
  "120.problem.en": "The drivable segment has a very acute turn at node A",
  "120.problem": "Sjízdný segment má příliš ostrý úhel zatočení v uzlu A",
  "120.solution.en": "Disable the sharp turn at node A or spread the segments at 30°",
  "120.solution": "Zakažte ostré zatočení nebo vytvořte mezi segmenty úhel nejméně 30°",
  "121.title.en": "Node B: Too sharp turn (slow)",
  "121.title": "Uzel B: Příliš ostrý úhel",
  "121.problem.en": "The drivable segment has a very acute turn at node B",
  "121.problem": "Sjízdný segment má příliš ostrý úhel zatočení v uzlu B",
  "121.solution.en": "Disable the sharp turn at node B or spread the segments at 30°",
  "121.solution": "Zakažte ostré zatočení nebo vytvořte mezi segmenty úhel nejméně 30°",
  "128.title.en": "User-defined custom check (green)",
  "128.title": "Uživatelem definované kontroly (zelená)",
  "128.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "128.problem": "Některá z nastavení segmentu souhlasí s uživatelsky definovanými kritérii (viz Nastavení→Vlastní)",
  "128.solution.en": "Solve the issue",
  "128.solution": "Vyřešit problém",
  "129.title.en": "User-defined custom check (blue)",
  "129.title": "Uživatelem definované kontroly (modrá)",
  "129.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "129.problem": "Některá z nastavení segmentu souhlasí s uživatelsky definovanými kritérii (viz Nastavení→Vlastní)",
  "129.solution.en": "Solve the issue",
  "129.solution": "Vyřešit problém",
  "130.enabled": true,
  "130.params": {
    "titleEN": "Alternate name without primary",
    "problemEN": "Segment has an alternate name but not the primary",
    "solutionEN": "Add primary name to allow deleting the secondary",
    "template": "${street}:${altStreet[#]}",
    "regexp": "/^:.+/",
  },
  "130.title.en": "Alternate name without primary",
  "130.title": "Alternativní jméno bez primárního",
  "130.problem.en": "Segment has an alternate name but not the primary",
  "130.problem": "Segment má alternativní jméno, ale ne primarní",
  "130.solution.en": "Add primary name to allow deleting the secondary",
  "130.solution": "Přidej primární jméno, aby šlo alternativní smazat",
  "131.enabled": true,
  "131.params": {
    "titleEN": "Unnamed higher class road",
    "problemEN": "Freeway, Major, Minor Highway or Primary Street without name (road number)",
    "solutionEN": "Assign a name to the road",
    "template": "${type}:${street}:${roundabout}:${length}",
    "regexp": "/^(2|3|6|7)::0:([6-9]|[1-5][0-9])[0-9]*$/",
  },
  "131.title.en": "Unnamed higher class road",
  "131.title": "Nepojmenovaná silnice vyšší třídy",
  "131.problem.en": "Freeway, Major, Minor Highway or Primary Street without name (road number)",
  "131.problem": "Dálnice, silnice I., II. nebo III. třídy nemá jméno (číslo silnice)",
  "131.solution.en": "Assign a name to the road",
  "131.solution": "Pojmenuj silnici",
  "132.enabled": true,
  "132.params": {
    "titleEN": "Missing road number",
    "problemEN": "Road has a name which is not a road number and the road number is not the first alternate name",
    "solutionEN": "Assign road name as the first alternate name",
    "template": "${type}:${street}:${altStreet[0]}:${length}",
    "regexp": "/^(2|3|6|7):.+[^0-9].+:(|.+[^0-9].+|[^D0-9].*):([6-9]|[1-5][0-9])[0-9]*$/",
  },
  "132.title.en": "Missing road number",
  "132.title": "Chybějící číslo silnice",
  "132.problem.en": "Road has a name which is not a road number and the road number is not the first alternate name",
  "132.problem": "Silnice má jméno, které není číslem silnice a toto číslo není ani první alternativní jméno",
  "132.solution.en": "Assign road name as the first alternate name",
  "132.solution": "Nastav číslo silnice jako první alternativní jméno",
  "133.enabled": true,
  "133.params": {
    "titleEN": "Alternate name for the road number",
    "problemEN": "Street name must be always the primary name and the road number the alternate name",
    "solutionEN": "Switch the primary and alternate name",
    "template": "${type}:${street}:${altStreet[0]}",
    "regexp": "/^(2|3|6|7):D?[0-9]+[a-zA-Z]?:.+$/",
  },
  "133.title.en": "Alternate name for the road number",
  "133.title": "Alternativní jméno k číslu silnice",
  "133.problem.en": "Street name must be always the primary name and the road number the alternate name",
  "133.problem": "Jméno ulice musí být vždy primární, číslo silnice první alternativní",
  "133.solution.en": "Switch the primary and alternate name",
  "133.solution": "Přehoď primární a alternativní jméno",
  "134.enabled": true,
  "134.params": {
    "titleEN": "Alternate road name outside of city",
    "problemEN": "Road out of any city has an alternate name",
    "solutionEN": "Check if it's OK or delete the alternate name",
    "template": "${city}:${altStreet[#]}",
    "regexp": "/^:.+$/",
  },
  "134.title.en": "Alternate road name outside of city",
  "134.title": "Alternativní jméno silnice mimo obec",
  "134.problem.en": "Road out of any city has an alternate name",
  "134.problem": "Silnice je mimo obec a má alternativní jméno",
  "134.solution.en": "Check if it's OK or delete the alternate name",
  "134.solution": "Zkontroluj, zda je to OK, případně alternativní jméno smaž",
  "135.enabled": true,
  "135.params": {
    "titleEN": "Alternate name within city doesn't have city assigned",
    "problemEN": "Primary name has city assigned but some of alternate name hasn't",
    "solutionEN": "Assign city to the alternate name; if the street name is a duplicate delete the alternate name without city",
    "template": "${city}:${altStreet[0]}:#${altCity[#]}#",
    "regexp": "/^.+:.+:.*##.*/",
  },
  "135.title.en": "Alternate name within city doesn't have city assigned",
  "135.title": "Alternativní název v obci nemá nastavenou obec",
  "135.problem.en": "Primary name has city assigned but some of alternate name hasn't",
  "135.problem": "Primární název má nastavené jméno obce, ale některý z alternativních názvů ne",
  "135.solution.en": "Assign city to the alternate name; if the street name is a duplicate delete the alternate name without city",
  "135.solution": "Nastav obec do alternativního názvu, pokud je název ulice duplicitní, název bez obce smaž",
  "136.enabled": true,
  "136.params": {
    "titleEN": "Named segment outside of a city",
    "problemEN": "Segment has street name but not a city name",
    "solutionEN": "Assign a city name or delete the street name",
    "template": "${type}:${city}:${street}",
    "regexp": "/^(1|5|8|10|16|17|20)::.+/",
  },
  "136.title.en": "Named segment outside of a city",
  "136.title": "Pojmenovaný segment mimo obec",
  "136.problem.en": "Segment has street name but not a city name",
  "136.problem": "Segment má název ulice, ale ne název města",
  "136.solution.en": "Assign a city name or delete the street name",
  "136.solution": "Nastav obec nebo smaž název města",
  "137.enabled": true,
  "137.severity": "warning",
  "137.solutionLink": "W:Czech/Co_zakreslit_a_co_ne#.C5.BDeleznice",
  "137.params": {
    "titleEN": "Incorrect Railroad Direction",
    "problemEN": "The direction of the railroad is not correct",
    "solutionEN": "Change the direction of the segment to Two way (⇆)",
    "template": "${typeRank}:${direction}",
    "regexp": "/^2:[^3]/"
  },    
  "137.title.en": "Incorrect Railroad Direction",
  "137.title": "Nesprávný směr železnice",
  "137.problem.en": "The direction of the railroad is not correct",
  "137.problem": "Železnice má nastaven nesprávný směr",
  "137.solution.en": "Change the direction of the segment to Two way (⇆)",
  "137.solution": "Nastav směr segmentu na obousměrný (⇆)",
  "138.enabled": true,
  "138.severity": "warning",
  "138.solutionLink": "W:Czech/Co_zakreslit_a_co_ne#.C5.BDeleznice",
  "138.params": {
    "titleEN": "Incorrect Railroad Lock",
    "problemEN": "The  Railroad Lock is not locked correctly",
    "solutionEN": "Railroads should always be locked at level 2",
    "template": "${typeRank}:${lock}",
    "regexp": "/^2:[^(2|3|4|5|6)]/"
  },
  "138.title.en": "Incorrect Railroad Lock",
  "138.title": "Chybějící zámek na železnici",
  "138.problem.en": "The  Railroad Lock is not locked correctly",
  "138.problem": "Segment železnice by měl být uzamčen alespoň na úroveň 2",
  "138.solution.en": "Railroads should always be locked at level 2",
  "138.solution": "Uzamkněte segment",
  "139.enabled": true,
  "139.severity": "warning",
  "139.solutionLink": "W:Czech/Co_zakreslit_a_co_ne#.C5.BDeleznice",
  "139.params": {
    "titleEN": "Incorrect Railroad Name",
    "problemEN": "The railroad should not be blank for default",
    "solutionEN": "In the address properties change the street name to 'Railroad' or the owner of the railroad.",
    "template": "${typeRank}:${street}",
    "link":"test",
    "regexp": "/^2:$/"
  },
  "139.title.en": "Incorrect Railroad Name",
  "139.title": "Chybějící název železnice",
  "139.problem.en": "The railroad should not be blank for default",
  "139.problem": "Název železnice nesmí být prázdný",
  "139.solution.en": "In the address properties change the street name to 'Railroad' or the owner of the railroad.",
  "139.solution": "V nastavení adresy změň název ulice na jednu z možností (xxx = číslo tratě): 'Železnice', 'Železnice xxx', 'Železnice xxx/xxx', 'žel. vlečka' nebo 'žel. vlečka Název'",
  "150.enabled": true,
  "150.params": {
    "n": 4
  },
  "150.problemLink": "F:t=64980&p=572847#p572847",
  "150.title.en": "No lock on Freeway",
  "150.title": "Chybějící zámek na dálnici",
  "150.problem.en": "The Freeway segment should be locked at least to Lvl ${n}",
  "150.problem": "Segment dálnice by měl být uzamčen alespoň na úroveň ${n}",
  "150.solution.en": "Lock the segment",
  "150.solution": "Uzamkněte segment",
  "151.enabled": true,
  "151.params": {
    "n": 4
  },
  "151.problemLink": "F:t=64980&p=572847#p572847",
  "151.title.en": "No lock on Major Highway",
  "151.title": "Chybějící zámek na silnici I. třídy",
  "151.problem.en": "The Major Highway segment should be locked at least to Lvl ${n}",
  "151.problem": "Silnice I. třídy by měla být uzamčena alespoň na úroveň ${n}",
  "151.solution.en": "Lock the segment",
  "151.solution": "Uzamkněte segment",
  "152.enabled": true,
  "152.params": {
    "n": 3
  },
  "152.problemLink": "F:t=64980&p=572847#p572847",
  "152.title.en": "No lock on Minor Highway",
  "152.title": "Chybějící zámek na silnici II. třídy",
  "152.problem.en": "The Minor Highway segment should be locked at least to Lvl ${n}",
  "152.problem": "Silnice II. třídy by měla být uzamčena alespoň na úroveň ${n}",
  "152.solution.en": "Lock the segment",
  "152.solution": "Uzamkněte segment",
  "153.enabled": true,
  "153.params": {
    "n": 4
  },
  "153.problemLink": "F:t=64980&p=572847#p572847",
  "153.title.en": "No lock on Ramp",
  "153.title": "Chybějící zámek na rampě",
  "153.problem.en": "The Ramp segment should be locked at least to Lvl ${n}",
  "153.problem": "Segment rampy by měl být uzamčen alespoň na úroveň ${n}",
  "153.solution.en": "Lock the segment",
  "153.solution": "Uzamkněte segment",
  "154.enabled": true,
  "154.params": {
    "n": 2
  },
  "154.problemLink": "F:t=64980&p=572847#p572847",
  "154.title.en": "No lock on Primary Road",
  "154.title": "Chybějící zámek na silnici III. třídy",
  "154.problem.en": "The Primary Road segment should be locked at least to Lvl ${n}",
  "154.problem": "Silnice III. třídy by měla být uzamčena alespoň na úroveň ${n}",
  "154.solution.en": "Lock the segment",
  "154.solution": "Uzamkněte segment",
  "167.enabled": true,
  "167.solutionLink": "W:Czech/Co_zakreslit_a_co_ne#.C5.BDeleznice",
  "167.severity": "warning",
  "167.params": {
    "titleEN": "Incorrect Railroad Name",
    "problemEN": "The railroad is not named correctly",
    "solutionEN": "Railroads must contain the owner company name or 'Railroad'",
    "regexp": "!/^(Železnice|Železnice [0-9]{3}|Železnice [0-9]{3}(/[0-9]{3}){0,9}|žel\. vlečka|žel\. vlečka .+)$/",
    },
  "167.title.en": "Incorrect Railroad Name",
  "167.title": "Nesprávný název železnice",
  "167.problem.en": "The railroad is not named correctly",
  "167.problem": "Název železnice není správný",
  "167.solution.en": "Railroads must contain the owner company name or 'Railroad'",
  "167.solution": "V nastavení adresy změň název ulice na jednu z možností (xxx = číslo tratě): 'Železnice', 'Železnice xxx', 'Železnice xxx/xxx', 'žel. vlečka' nebo 'žel. vlečka Název'",
  "170.enabled": true,
  "170.params": {
    "regexp": "/^(?!(alej|bratranců|bratří|bří|dr\\.|gen\\.|generála|kapitána|kpt\\.|krále|majora|mjr\\.|most|nábř\\.|nábřeží|nám\\.|náměstí|park|plk\\.|plukovníka|podplukovníka|por\\.|poručíka|pplk\\.|prap\\.|praporčíka|prof\\.|promenáda|sad|sady|sídl\\.|sídliště|tř\\.|třída|tunel|ul\\.|ulice|zahrada) [^a-z])[a-z]/"
  },
  "170.title.en": "Lowercase street name",
  "170.title": "Název ulice malým písmenem",
  "170.problem.en": "The street name starts with a lowercase word",
  "170.problem": "Název ulice začíná malým písmenem",
  "170.solution.en": "Correct lettercase in the street name",
  "170.solution": "Opravte velikost písmen",
  "172.title.en": "Unneeded spaces in street name",
  "172.title": "Nadbytečné mezery v názvu ulice",
  "172.problem.en": "Leading/trailing/double space in the street name",
  "172.problem": "Mezera v názvu ulice (před/za/dvojitá)",
  "172.solution.en": "Remove unneeded spaces from the street name",
  "172.solution": "Odstraňte nadbytečné mezery v názvu ulice",
  "173.title.en": "No space before/after street abbreviation",
  "173.title": "Chybějící mezera před/za zkratkou ulice",
  "173.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the street name",
  "173.problem": "Chybějící mezera před ('1943r.') nebo za ('st.Jan') ve zkratce názvu ulice",
  "173.solution.en": "Add a space before/after the abbreviation",
  "173.solution": "Doplňte mezeru před/za zkratku ulice",
  "175.title.en": "Empty street name",
  "175.title": "Prázdné jméno ulice",
  "175.problem.en": "The street name has only space characters or a dot",
  "175.problem": "Ulice má v názvu pouze mezeru nebo tečku",
  "175.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' OR set a proper street name",
  "175.solution": "V nastavení adresy zaškrtněte 'Nic' vedle názvu, klikněte na 'Potvrdit' NEBO nastavte správný název ulice",
  "190.params": {
  "regexp": "/^[a-z]/",
  },
  "190.title.en": "Lowercase city name",
  "190.title": "Název města malým",
  "190.problem.en": "The city name starts with a lowercase letter",
  "190.problem": "Název města začíná malým písmenem",
  "190.solution.en": "Use this form to rename the city",
  "190.solution": "Použijte tento formulář k přejmenování města",
  "192.title.en": "Unneeded spaces in city name",
  "192.title": "Nadbytečné mezery v názvu města",
  "192.problem.en": "Leading/trailing/double space in the city name",
  "192.problem": "Mezera v názvu města (před/za/dvojitá)",
  "192.solution.en": "Use this form to rename the city",
  "192.solution": "Použijte tento formulář k přejmenování města",
  "193.title.en": "No space before/after city abbreviation",
  "193.title": "Chybějící mezera před/za zkratkou města",
  "193.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the city name",
  "193.problem": "Chybějící mezera před ('1943r.') nebo za ('st.Jan') ve zkratce názvu města",
  "193.solution.en": "Use this form to rename the city",
  "193.solution": "Použijte tento formulář k přejmenování města",
  "200.title.en": "Node A: Unconfirmed turn on minor road",
  "200.title": "Uzel A: Nepotvrzené odbočení na místní komunikaci",
  "200.problem.en": "The minor drivable segment has an unconfirmed (soft) turn at node A",
  "200.problem": "Segment silnice nižší třídy má nepotvrzené odbočení v uzlu A",
  "200.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "200.solution": "Klikněte na odbočení označené fialovým otazníkem a potvrďte ho. Poznámka: možná budete muset změnit segment na 'Obousměrný', abyste viděli toto odbočení",
  "201.title.en": "Node A: Unconfirmed turn on primary road",
  "201.title": "Uzel A: Nepotvrzené odbočení na významné silnici",
  "201.problem.en": "The primary segment has an unconfirmed (soft) turn at node A",
  "201.problem": "Segment silnice vyšší třídy má nepotvrzené odbočení v uzlu A",
  "201.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "201.solution": "Klikněte na odbočení označené fialovým otazníkem a potvrďte ho. Poznámka: možná budete muset změnit segment na 'Obousměrný', abyste viděli toto odbočení"
};
