// ==UserScript==
// @name                WME Validator Localization for Slovakia
// @version             1.0.2
// @description         This script localizes WME Validator for Slovakia. You also need main package (WME Validator) installed.
// @match               https://editor-beta.waze.com/*editor/*
// @match               https://www.waze.com/*editor/*
// @grant               none
// @run-at              document-start
// @namespace           https://greasyfork.org/users/3173
// ==/UserScript==
//
/*
  Please translate all the lines marked with "TODO: "
  Please DO NOT change ".en" properties. To override english text use "titleEN",
  "problemEN" and "solutionEN" properties (see an example below).

  See Settings->About->Available checks for complete list of checks and their params.

  Examples:

  Enable #170 "Lowercase street name" but allow lowercase "exit" and "to":
    "170.enabled": true,
    "170.params": {
        "regexp": "/^((exit|to) )?[a-z]/",
    "},

  Enable #130 "Custom check" to find a dot in street names, but allow dots at Ramps:
    "130.enabled": true,
    "130.params": {
        "titleEN": "Street name with a dot",
        "problemEN": "There is a dot in the street name (excluding Ramps)",
        "solutionEN": "Expand the abbreviation or remove the dot",
        "template": "${type}:${street}",
        "regexp": "D/^[^4][0-9]?:.*\\./",
    },
    *Note: use D at the beginning of RegExp to enable debugging on JS console.
    *Note: do not forget to escape backslashes in strings, i.e. use "\\" instead of "\".
*/

window.WME_Validator_Slovakia = {
  ".country": "Slovakia",
  ".codeISO": "SK",
  ".author": "ChoseS",
  ".updated": "2014-07-06",
  ".link": "https://greasyfork.org/scripts/2990-wme-validator-localization-for-slovakia",
  ".lng": "SK",
  "city.consider.en": "consider this city name:",
  "city.consider": "zváž tento názov mesta:",
  "city.1.en": "city name is too short",
  "city.1": "meno mesta je príliš krátke",
  "city.2.en": "expand the abbreviation",
  "city.2": "rozbaľ skratku",
  "city.3.en": "complete short name",
  "city.3": "doplň krátky názov",
  "city.4.en": "complete city name",
  "city.4": "doplň názov mesta",
  "city.5.en": "correct letter case",
  "city.5": "oprav výšku písma",
  "city.6.en": "check word order",
  "city.6": "skontroluj poradie slov",
  "city.7.en": "check abbreviations",
  "city.7": "skontroluj skratku",
  "city.8a.en": "add county name",
  "city.8a": "pridaj nazov oblasti",
  "city.8r.en": "remove county name",
  "city.8r": "odstráň názov oblasti",
  "city.9.en": "check county name",
  "city.9": "skontroluj názov oblasti",
  "city.10a.en": "add a word",
  "city.10a": "pridaj slovo",
  "city.10r.en": "remove a word",
  "city.10r": "odstráň slovo",
  "city.11.en": "add county code",
  "city.11": "pridaj kód oblasti",
  "city.12.en": "identical names, but different city IDs",
  "city.12": "rovnaké názvy, ale rozdielné ID miest",
  "city.13a.en": "add a space",
  "city.13a": "pridať medzeru",
  "city.13r.en": "remove a space",
  "city.13r": "odstrániť medzeru",
  "city.14.en": "check the number",
  "city.14": "skontroluj číslo",
  "props.skipped.title.en": "The segment is not checked",
  "props.skipped.title": "Segment nie je skontrolovaný",
  "props.skipped.problem.en": "The segment is modified after 2014-05-01 AND locked for you, so Validator did not check it",
  "props.skipped.problem": "Segment bol zmenený po 1.5.2014 a uzamknutý pre Vás, takže ho Validator neskotroloval",
  "err.regexp.en": "Error parsing option for check #${n}:",
  "err.regexp": "Chyba pri analýze kontroly #${n}:",
  "props.disabled.en": "WME Validator is disabled",
  "props.disabled": "WME Validator je vypnutý",
  "props.limit.title.en": "Too many issues reported",
  "props.limit.title": "Hlásených príliš veľa chýb",
  "props.limit.problem.en": "There are too many issues reported, so some of them might not be shown",
  "props.limit.problem": "Je tu hlásených príliš veľa chýb, Takže niektoré nemusia byť zobrazené",
  "props.limit.solution.en": "Deselect the segment and stop scanning process. Then click red '✘' (Clear report) button",
  "props.limit.solution": "Zruš označenie segmentu a zastav skenovanie. Potom klikni na červené tlačidlo '✘' (vymaž hlásenie)",
  "props.reports.en": "reports",
  "props.reports": "hlásenie",
  "props.noneditable.en": "You cannot edit this segment",
  "props.noneditable": "Nemôžeš editovať tento segment",
  "report.save.en": "Save this report",
  "report.save": "Uložiť toto hlásenie",
  "report.list.andUp.en": "and up",
  "report.list.andUp": "a až",
  "report.list.severity.en": "Severity:",
  "report.list.severity": "Obťiažnosť:",
  "report.list.reportOnly.en": "only in report",
  "report.list.reportOnly": "iba v hlásení",
  "report.list.forEditors.en": "For editors level:",
  "report.list.forEditors": "Pre editorov s levelom:",
  "report.list.forCountries.en": "For countries:",
  "report.list.forCountries": "Pre krajiny:",
  "report.list.forStates.en": "For states:",
  "report.list.forStates": "Pre štáty:",
  "report.list.forCities.en": "For cities:",
  "report.list.forCities": "Pre mestá:",
  "report.list.params.en": "Params to configure in localization pack:",
  "report.list.params": "Parametre nastavenia lokalizačného balíčka:",
  "report.list.params.set.en": "Current configuration for ${country}:",
  "report.list.params.set": "Aktuálne nastavenie pre ${country}:",
  "report.list.enabled.en": "${n} checks are enabled for",
  "report.list.enabled": "${n} kontroly sú povolené pre",
  "report.list.disabled.en": "${n} checks are disabled for",
  "report.list.disabled": "${n} kontroly nie sú povolené pre",
  "report.list.total.en": "There are ${n} checks available",
  "report.list.total": "Celkom ${n} dostupných kontrol",
  "report.list.title.en": "Complete List of Checks for",
  "report.list.title": "Celkový prehľad kontról pre",
  "report.list.see.en": "See",
  "report.list.see": "Pozri",
  "report.list.checks.en": "Settings->About->Available checks",
  "report.list.checks": "Nastavenia->O...->Dostupné kontroly",
  "report.list.fallback.en": "Localization Fallback Rules:",
  "report.list.fallback": "Pravidlá lokalizácie:",
  "report.and.en": "and",
  "report.and": "a",
  "report.segments.en": "Total number of segments checked:",
  "report.segments": "Celkový počet skontrolovaných segmentov:",
  "report.customs.en": "Custom checks matched (green/blue):",
  "report.customs": "Uživateľská kontrola (zelená/modrá):",
  "report.reported.en": "Reported",
  "report.reported": "Hlásené",
  "report.errors.en": "errors",
  "report.errors": "chyby",
  "report.warnings.en": "warnings",
  "report.warnings": "upozornenie",
  "report.notes.en": "notes",
  "report.notes": "poznámky",
  "report.link.wiki.en": "wiki",
  "report.link.wiki": "wiki",
  "report.link.forum.en": "forum",
  "report.link.forum": "fórum",
  "report.link.other.en": "link",
  "report.link.other": "odkaz",
  "report.contents.en": "Contents:",
  "report.contents": "obsah:",
  "report.summary.en": "Summary",
  "report.summary": "Súhrn",
  "report.title.en": "WME Validator Report",
  "report.title": "Hlásenie WME Validatora",
  "report.share.en": "to Share",
  "report.share": "zdielať",
  "report.generated.by.en": "generated by",
  "report.generated.by": "vytvorené ..",
  "report.generated.on.en": "on",
  "report.generated.on": "na",
  "report.source.en": "Report source:",
  "report.source": "Zdroj hlásenia:",
  "report.filter.duplicate.en": "duplicate segments",
  "report.filter.duplicate": "Duplicitný segment",
  "report.filter.streets.en": "Streets and Service Roads",
  "report.filter.streets": "Ulica a obslužná cesta",
  "report.filter.other.en": "Other drivable and Non-drivable",
  "report.filter.other": "Ostatné zjazdné a nezjazdné cesty",
  "report.filter.noneditable.en": "non-editable segments",
  "report.filter.noneditable": "needitovateľné segmenty",
  "report.filter.notes.en": "notes",
  "report.filter.notes": "poznámky",
  "report.filter.title.en": "Filter:",
  "report.filter.title": "Filter:",
  "report.filter.excluded.en": "are excluded from this report.",
  "report.filter.excluded": "sú vylúčený z tohto hlásenia.",
  "report.search.updated.by.en": "updated by",
  "report.search.updated.by": "aktualizované",
  "report.search.updated.since.en": "updated since",
  "report.search.updated.since": "aktualizované od",
  "report.search.city.en": "from",
  "report.search.city": "od",
  "report.search.reported.en": "reported as",
  "report.search.reported": "hlásené ako",
  "report.search.title.en": "Search:",
  "report.search.title": "Vyhladávanie:",
  "report.search.only.en": "only segments",
  "report.search.only": "iba segmenty",
  "report.search.included.en": "are included into the report.",
  "report.search.included": "sú zahrnuté v tomto hlásení.",
  "report.beta.warning.en": "WME Beta Warning!",
  "report.beta.warning": "WME Beta Upozornenie!",
  "report.beta.text.en": "This report is generated in beta WME with beta permalinks.",
  "report.beta.text": "Toto hlásenie je vytvorené pomocou WME beta s beta odkazmi.",
  "report.beta.share.en": "Please do not share those permalinks!",
  "report.beta.share": "Prosím nezdieľajte tieto odkazy!",
  "report.size.warning.en": "<b>Warning!</b><br>The report is ${n} characters long so <b>it will not fit</b> into a single forum or private message.\n<br>Please add <b>more filters</b> to reduce the size of the report.",
  "report.size.warning": "<b>Upozornenie!</b><br>Hlásenie je ${n} znakov dlhé, <b>takže sa nevojde</b> do jednej správy - súkromnej či na fórum.\n<br>Prosím pridajte <b>viac</b> ku zníženiu veľkosti hlásenia.",
  "report.note.limit.en": "* Note: there were too many issues reported, so some of them are not counted in the summary.",
  "report.note.limit": "Pozn.: je tu hlásených veľa chýb, takže niektoré nie sú započítané do štatistýk.",
  "report.forum.en": "To motivate further development please leave your comment on the",
  "report.forum": "Pre motiváciu ďalších vývojárov prosím zanechaj svoj komentár v",
  "report.forum.link.en": "Waze forum thread.",
  "report.forum.link": "vlákne Waze fóra.",
  "report.thanks.en": "Thank you for using WME Validator!",
  "report.thanks": "Ďakujeme za využívanie WME Validátora!",
  "msg.limit.segments.en": "There are too many segments.\n\nClick 'Show report' to review the report, then\n",
  "msg.limit.segments": "Je tu veľa segmentov.\n\nStlač 'Ukáž hlásenie k náhľadu hlásenia, potom\n",
  "msg.limit.segments.continue.en": "click '▶' (Play) to continue.",
  "msg.limit.segments.continue": "stlač '▶' (Spustiť) pokračovanie.",
  "msg.limit.segments.clear.en": "click '✘' (Clear) to clear the report.",
  "msg.limit.segments.clear": "stlač '✘' (vymazať) pre vymazanie hlásenia.",
  "msg.pan.text.en": "Pan around to validate the map",
  "msg.pan.text": "Posunte mapu pre kontrolu mapy",
  "msg.zoomout.text.en": "Zoom out to start WME Validator",
  "msg.zoomout.text": "Oddiaľ mapu pre spustenie WME Validátora",
  "msg.click.text.en": "Click '▶' (Play) to validate visible map area",
  "msg.click.text": "Stlač '▶' (Spusti) pre kontrolu viditeľnej oblasti mapy",
  "msg.autopaused.en": "autopaused",
  "msg.autopaused": "autopauza",
  "msg.autopaused.text.en": "Auto paused! Click '▶' (Play) to continue.",
  "msg.autopaused.text": "Auto pauza! Stlač '▶' (Spustiť) pre pokračovanie.",
  "msg.autopaused.tip.en": "WME Validator automatically paused on map drag or window size change",
  "msg.autopaused.tip": "WME Validátor automaticky zastaví pri posune mapy alebo zmene veľkosti okna",
  "msg.finished.text.en": "Click <b>'Show report'</b> to review map issues",
  "msg.finished.text": "Stlač <b>'Ukáž hlásenie'</b> k prehľadu chýb v mape",
  "msg.finished.tip.en": "Click '✉' (Share) button to post report on a\nforum or in a private message",
  "msg.finished.tip": "Stlač '✉' (Zdielať) k odoslaniu hlásenia a\nfórum alebo v súkromnej správe",
  "msg.noissues.text.en": "Finished! No issues found!",
  "msg.noissues.text": "Dokončené! Žiadne chyby nenájdené!",
  "msg.noissues.tip.en": "Try to uncheck some filter options or start WME Validator over another map area!",
  "msg.noissues.tip": "Skús zrušiť niektoré kritéria alebo spusti WME Validator nad inou mapovou oblasťou!",
  "msg.scanning.text.en": "Scanning! Finishing in ~ ${n} min",
  "msg.scanning.text": "Prehľadávam! Dokončenie behom ~ ${n} minút",
  "msg.scanning.text.soon.en": "Scanning! Finishing in a minute!",
  "msg.scanning.text.soon": "Prehľadávam! Dokončenie behom minúty!",
  "msg.scanning.tip.en": "Click 'Pause' button to pause or '■' (Stop) to stop",
  "msg.scanning.tip": "Stlač 'Pauza' k pozastaveniu alebo '■' (Stop) k zastaveniu",
  "msg.starting.text.en": "Starting! Layers are off to scan faster!",
  "msg.starting.text": "Začínam! Vypnutie vrstiev zrýchli prehľadávanie!",
  "msg.starting.tip.en": "Use 'Pause' button to pause or '■' button to stop",
  "msg.starting.tip": "Použi 'Pauza' k pozastaveniu alebo '■' k zastaveniu",
  "msg.paused.text.en": "On pause! Click '▶' (Play) button to continue.",
  "msg.paused.text": "Pozastavené! Stlač '▶' (Spustiť) pre pokračovanie.",
  "msg.paused.tip.en": "To view the report click 'Show report' button (if available)",
  "msg.paused.tip": "Pre prehranie hlásenia stlač 'Ukáž hlásenie' (ak je dostupné)",
  "msg.continuing.text.en": "Continuing!",
  "msg.continuing.text": "Pokračujeme!",
  "msg.continuing.tip.en": "WME Validator will continue from the location it was paused",
  "msg.continuing.tip": "WME Validator bude pokračovať z miesta, kde bol prerušený",
  "msg.settings.text.en": "Click <b>'Back'</b> to return to main view",
  "msg.settings.text": "Stlač <b>'Späť'</b> pre návrat na hlavný prehľad",
  "msg.settings.tip.en": "Click 'Reset defaults' button to reset all settings in one click!",
  "msg.settings.tip": "Stlač 'Obnov predvolené' k obnoveniu všetkých nastavení na predvolené!",
  "msg.reset.text.en": "All filter options and settings have been reset to their defaults",
  "msg.reset.text": "Všetky filtre a nastavenia boli obnovené na ich predvolené hodnoty",
  "msg.reset.tip.en": "Click 'Back' button to return to main view",
  "msg.reset.tip": "Stlač 'Back' pre návrat na hlavný prehľad",
  "msg.textarea.pack.en": "This is a Greasemonkey/Tampermonkey script. You can copy and paste the text below into a <b>new .user.js file</b><br>or <b>paste it directly</b> into the Greasemonkey/Tampermonkey",
  "msg.textarea.pack": "Toto je Greasemonkey/Tampermonkey skript. Môžete je kopírovať a vložiť text do <b>nového .user.js súboru</b><br>alebo <b>ho vložiť priamo</b> do Greasemonkey/Tampermonkey",
  "msg.textarea.en": "Please copy the text below and then paste it into your forum post or private message",
  "msg.textarea": "Prosím skopírujte text nižšie a vložte ho ako príspevok na fórum alebo v súkromnej správe",
  "noaccess.text.en": "<b>Sorry,</b><br>You cannot use WME Validator over here.<br>Please check <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>the forum thread</a><br>for more information.",
  "noaccess.text": "<b>Ospravedlňujeme sa,</b><br>tu nemôžete použiť WME Validator.<br>Prosím pozrite si <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>vlákno na fóre</a><br>pre viac informácií.",
  "noaccess.tip.en": "Please check the forum thread for more information!",
  "noaccess.tip": "Prosím pozrite si vlákno na fóre pre viac informácií!",
  "tab.switch.tip.on.en": "Click to switch highlighting on (Alt+V)",
  "tab.switch.tip.on": "Stlač pre zapnutie zvýraznenia (Alt+V)",
  "tab.switch.tip.off.en": "Click to switch highlighting off (Alt+V)",
  "tab.switch.tip.off": "Stlač pre vypnutie zvýraznenia (Alt+V)",
  "tab.filter.text.en": "filter",
  "tab.filter.text": "filter",
  "tab.filter.tip.en": "Options to filter the report and highlighted segments",
  "tab.filter.tip": "Nastavenie pre filter hlásení a zvýraznenia segmentov",
  "tab.search.text.en": "search",
  "tab.search.text": "hladať",
  "tab.search.tip.en": "Advanced filter options to include only specific segments",
  "tab.search.tip": "Rozšírené nastavenie filtra pre výber určitých segmentov",
  "tab.help.text.en": "help",
  "tab.help.text": "pomoc",
  "tab.help.tip.en": "Need help?",
  "tab.help.tip": "Potrebuješ pomoc?",
  "filter.noneditables.text.en": "Exclude <b>non-editable</b> segments",
  "filter.noneditables.text": "Bez <b>needitovateľných</b> segmentov",
  "filter.noneditables.tip.en": "Do not report locked segments or\nsegments outside of your editable areas",
  "filter.noneditables.tip": "Nehlásiť uzamknuté segmenty alebo\nsegmenty mimo tvoju editovateľnú oblasť",
  "filter.duplicates.text.en": "Exclude <b>duplicate</b> segments",
  "filter.duplicates.text": "Bez <b>duplicitných</b> segmentov",
  "filter.duplicates.tip.en": "Do not show the same segment in different\nparts of report\n* Note: this option DOES NOT affect highlighting",
  "filter.duplicates.tip": "Nezobrazovať rovnaké segmenty v rôznych\nčastiach hlásenia\n* Pozn. toto nastavenie NEMÁ vplyv na zvýraznenie",
  "filter.streets.text.en": "Exclude <b>Streets and Service Roads</b>",
  "filter.streets.text": "Bez <b>Ulíc a obslužných komunikácií</b>",
  "filter.streets.tip.en": "Do not report Streets and Service Roads",
  "filter.streets.tip": "Nehlásiť ulice a obslužné komunikácie",
  "filter.other.text.en": "Exclude <b>Other drivable and Non-drivable</b>",
  "filter.other.text": "Bez <b>ostatných (ne)prejazdných komunikácií</b>",
  "filter.other.tip.en": "Do not report Dirt, Parking Lot, Private Roads\nand non-drivable segments",
  "filter.other.tip": "Nehlásiť chodníky, parkoviská, súkromné cesty\na ďalšie neprejazdné segmnety",
  "filter.notes.text.en": "Exclude <b>notes</b>",
  "filter.notes.text": "Bez <b>poznámok</b>",
  "filter.notes.tip.en": "Report only warnings and errors",
  "filter.notes.tip": "Hlásiť len upozornenia a chyby",
  "search.youredits.text.en": "Include <b>only your edits</b>",
  "search.youredits.text": "Zahrnúť <b>iba vlastné editácie</b>",
  "search.youredits.tip.en": "Include only segments edited by you",
  "search.youredits.tip": "Zahrnúť len Vami editované segmenty",
  "search.updatedby.text.en": "<b>Updated by*:</b>",
  "search.updatedby.text": "<b>Aktualizované*:</b>",
  "search.updatedby.tip.en": "Include only segments updated by the specified editor\n* Note: this option is available for country managers only\nThis field supports:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Note: you may use 'me' to match yourself",
  "search.updatedby.tip": "Zahrňuje len segmenty aktualizované určeným editorom\n* Pozn.: Táto možnosť je k dispozícii iba pre manažérov krajín\ n Toto pole odporuje: \ n - zoznamy: ja, otherEditor\n - zástupné znaky: svet*\n - negácia: !ja, *\n* Pozn.: môžeš použiť 'me', aby si mohol skontrolovať vlastné úpravy",
  "search.updatedby.example.en": "Example: me",
  "search.updatedby.example": "Napríklad: me",
  "search.updatedsince.text.en": "<b>Updated since:</b>",
  "search.updatedsince.text": "<b>Aktualizované od:</b>",
  "search.updatedsince.tip.en": "Include only segments edited since the date specified\nFirefox date format: YYYY-MM-DD",
  "search.updatedsince.tip": "Zahrňuje iba segmenty editované od určitého dátumu\nFormát dátumu: RRRR-MM-DD",
  "search.updatedsince.example.en": "YYYY-MM-DD",
  "search.updatedsince.example": "RRRR-MM-DD",
  "search.city.text.en": "<b>City name:</b>",
  "search.city.text": "<b>Názov mesta:</b>",
  "search.city.tip.en": "Include only segments with specified city name\nThis field supports:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
  "search.city.tip": "Zahrňuje len segmenty s určeným názvom mesta\nPole podporuje:\n - zoznamy: Paris, Meudon\n - zástupné znaky: Greater * Area\n - negácia: !Paris, *",
  "search.city.example.en": "Example: !Paris, *",
  "search.city.example": "Napríklad: !Paris, *",
  "search.checks.text.en": "<b>Reported as:</b>",
  "search.checks.text": "<b>Hlásené ako:</b>",
  "search.checks.tip.en": "Include only segments reported as specified\nThis field matches:\n - severities: errors\n - check names: New road\n - check IDs: 200\nThis field supports:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
  "search.checks.tip": "Zahrňuje iba segmenty, ktoré sú určené\nPole porovnáva:\n - dôležitosť: chyby\n - kontrola mien: Nová cesta\n - kontrola ID: 200\nPole podporuje:\n - zoznam: 36, 37\n - Zástupné znaky: *roundabout*\n - negácia: !unconfirmed*, *",
  "search.checks.example.en": "Example: reverse*",
  "search.checks.example": "Napríklad: opačné*",
  "help.text.en": "<b>Help Topics:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Ask your question on the forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">How to adjust Validator for your country</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">About the \"Might be Incorrect City Name\"</a>",
  "help.text": "<b>Témy nápovedy:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Napíš svoj dotaz na fóre</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Ako nastaviť Validator pre tvoju zem</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Ohľadne \"Might be Incorrect City Name\"</a>",
  "help.tip.en": "Open in a new browser tab",
  "help.tip": "Otvoriť na novej karte prehliadača",
  "button.scan.tip.en": "Start scanning current map area\n* Note: this might take few minutes",
  "button.scan.tip": "Spustiť prehľadávanie aktuálnej mapovej oblasti\n* Pozn.: môže to trvať niekoľko minút",
  "button.scan.tip.NA.en": "Zoom out to start scanning current map area",
  "button.scan.tip.NA": "Oddiaľ mapu pre spustenie prehľadávania aktuálnej mapovej oblasti",
  "button.pause.tip.en": "Pause scanning",
  "button.pause.tip": "Pozastaviť prehľadávanie",
  "button.continue.tip.en": "Continue scanning the map area",
  "button.continue.tip": "Pokračovať v prehľadávaní mapovej oblasti",
  "button.stop.tip.en": "Stop scanning and return to the start position",
  "button.stop.tip": "Zastaviť prehľadávanie a vrátiť sa na pôvodnú pozíciu",
  "button.clear.tip.en": "Clear report and segment cache",
  "button.clear.tip": "Vymazať cache hlásení a segmentov",
  "button.clear.tip.red.en": "There are too many reported segments:\n 1. Click 'Show report' to generate the report.\n 2. Click this button to clear the report and start over.",
  "button.clear.tip.red": "Je tu veľa nahlásených segmentov:\n 1. Stlač 'Ukázať hlásenie' pre vygenerovanie hlásenia.\n 2. Stlač tlačidlo pre vymazanie tohoto hlásenia a sprav nové hlásenie.",
  "button.report.text.en": "Show report",
  "button.report.text": "Ukáž hlásenie",
  "button.report.tip.en": "Apply the filter and generate HTML report in a new tab",
  "button.report.tip": "Použiť filter a vytvoriť HTML hlásenie v novom okne",
  "button.BBreport.tip.en": "Share the report on Waze forum or in a private message",
  "button.BBreport.tip": "Sdielať hlásenie na Waze fóre alebo v súkromnej správe",
  "button.settings.tip.en": "Configure settings",
  "button.settings.tip": "Konfigurácia nastavení",
  "tab.custom.text.en": "custom",
  "tab.custom.text": "Vlastné",
  "tab.custom.tip.en": "User-defined custom checks settings",
  "tab.custom.tip": "Vlastné nastavenie kontroly užívateľom",
  "tab.settings.text.en": "Settings",
  "tab.settings.text": "Nastavenie",
  "tab.scanner.text.en": "scanner",
  "tab.scanner.text": "prehľadávania",
  "tab.scanner.tip.en": "Map scanner settings",
  "tab.scanner.tip": "Nastavenie prehľadávania mapy",
  "tab.about.text.en": "about</span>",
  "tab.about.text": "O..</span>",
  "tab.about.tip.en": "About WME Validator",
  "tab.about.tip": "O WME Validatore",
  "scanner.sounds.text.en": "Enable sounds",
  "scanner.sounds.text": "Zapnúť zvuky",
  "scanner.sounds.tip.en": "Bleeps and the bloops while scanning",
  "scanner.sounds.tip": "Pípnutie počas prehľadávania",
  "scanner.sounds.NA.en": "Your browser does not support AudioContext",
  "scanner.sounds.NA": "Váš prehliadač nepodporuje zvukový obsah",
  "scanner.highlight.text.en": "Highlight issues on the map",
  "scanner.highlight.text": "Zvýrazniť chyby v mape",
  "scanner.highlight.tip.en": "Highlight reported issues on the map",
  "scanner.highlight.tip": "Zobraziť hlásené chyby na mape",
  "scanner.slow.text.en": "Enable \"slow\" checks",
  "scanner.slow.text": "Povoliť \"pomalú\" kontrolu",
  "scanner.slow.tip.en": "Enables deep map analysis\n* Note: this option might slow down the scanning process",
  "scanner.slow.tip": "Povoliť hlbšiu mapovú analýzu\n* Pozn.: toto nastavenie môže spomaliť prehľadávací proces",
  "scanner.ext.text.en": "Report external highlights",
  "scanner.ext.text": "Hlásenie externých zvýraznení",
  "scanner.ext.tip.en": "Report segments highlighted by WME Toolbox or WME Color Highlights",
  "scanner.ext.tip": "Hlásiť segmenty zvýraznené pomocou WME Toolbox alebo WME Color Highlights",
  "advanced.twoway.text.en": "WME: Two-way segments by default",
  "advanced.twoway.text": "WME: obojsmerné segmenty ako predvolené",
  "advanced.twoway.tip.en": "Newly created streets in WME are bidirectional by default",
  "advanced.twoway.tip": "Novo vytvárané ulice vo WME budú obojsmerné ako predvolené",
  "custom.template.text.en": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Custom template</a>",
  "custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Vlastná šablóna</a>",
  "custom.template.tip.en": "User-defined custom check expandable template.\n\nYou may use the following expandable variables:\nAddress:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nSegment properties:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nHelpers:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nConnectivity:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.tip": "Vlastná užívateľsky rozšíriteľná šablóna kontról.\n\nMôžete použiť nasledujúce rozširujúce premenné:\nAddresa:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nParametre segmentov:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nPomocníci:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nPripojenie:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.example.en": "Example: ${street}",
  "custom.template.example": "Napríklad: ${street}",
  "custom.regexp.text.en": "Custom <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
  "custom.regexp.text": "Vlastné <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
  "custom.regexp.tip.en": "User-defined custom check regular expression to match the template.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
  "custom.regexp.tip": "Uživateľsky definované výrazy pre kontrolu.\n\nCitlivosť písmen: /regexp/i\nNegácia (nezhoduje sa): !/regexp/\nLog informácie: D/regexp/",
  "custom.regexp.example.en": "Example: !/.+/",
  "custom.regexp.example": "Napríklad: !/.+/",
  "about.tip.en": "Open link in a new tab",
  "about.tip": "Otvoriť odkaz na novej karte",
  "button.reset.text.en": "Reset defaults",
  "button.reset.text": "Pôvodné nastavenia",
  "button.reset.tip.en": "Revert filter options and settings to their defaults",
  "button.reset.tip": "Vrátiť filtre a nastavenia na pôvodné",
  "button.list.text.en": "Available checks...",
  "button.list.text": "Dostupné kontroly...",
  "button.list.tip.en": "Show a list of checks available in WME Validator",
  "button.list.tip": "Zobraz zoznam dostupných kontrôl v WME Validátore",
  "button.wizard.tip.en": "Create localization package",
  "button.wizard.tip": "Vytvoriť lokalizačný balíček",
  "button.back.text.en": "Back",
  "button.back.text": "Späť",
  "button.back.tip.en": "Close settings and return to main view",
  "button.back.tip": "Zavrieť nastavenia a vrátiť sa na hlavné zobrazenie",
  "1.title.en": "WME Toolbox: Roundabout which may cause issues",
  "1.title": "WME Toolbox: Kruhový objazd, môže spôsobyť chyby",
  "1.problem.en": "Junction IDs of the roundabout segments are not consecutive",
  "1.problem": "Hodnoty ID križovatiek segmentu kruhového objazdu nie sú po sebe nasledujúce",
  "1.solution.en": "Redo the roundabout",
  "1.solution": "Uprav kruhový objazd",
  "2.title.en": "WME Toolbox: Simple segment",
  "2.title": "WME Toolbox: Jednoduchý segment",
  "2.problem.en": "The segment has unneeded geometry nodes",
  "2.problem": "Segment obsahuje nepotrebné uzle",
  "2.solution.en": "Simplify segment geometry by hovering mouse pointer and pressing \"d\" key",
  "2.solution": "Zjednoduš geometriu pridržaním ukazovateľa myši nad segmentom a stlač klávesu \"d\"",
  "3.title.en": "WME Toolbox: Lvl 2 lock",
  "3.title": "WME Toolbox: zámok Lvl 2",
  "3.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "3.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "4.title.en": "WME Toolbox: Lvl 3 lock",
  "4.title": "WME Toolbox: zámok Lvl 3",
  "4.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "4.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "5.title.en": "WME Toolbox: Lvl 4 lock",
  "5.title": "WME Toolbox: zámok Lvl 4",
  "5.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "5.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "6.title.en": "WME Toolbox: Lvl 5 lock",
  "6.title": "WME Toolbox: zámok Lvl 5",
  "6.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "6.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "7.title.en": "WME Toolbox: Lvl 6 lock",
  "7.title": "WME Toolbox: zámok Lvl 6",
  "7.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "7.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "8.title.en": "WME Toolbox: House numbers",
  "8.title": "WME Toolbox: Čísla domov",
  "8.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "8.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "9.title.en": "WME Toolbox: Segment with time restrictions",
  "9.title": "WME Toolbox: Segment s časovým obmedzením",
  "9.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "9.problem": "Segment zvýraznený pomocou WME Toolbox. Žiadny problém",
  "13.title.en": "WME Color Highlights: Editor lock",
  "13.title": "WME Color Highlights: Editorský zámok",
  "13.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "13.problem": "Segment zvýraznený pomocou Color Highlights. Žiadny problém",
  "14.title.en": "WME Color Highlights: Toll road / One way road",
  "14.title": "WME Color Highlights: Spoplatnený úsek / jednosmerka",
  "14.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "14.problem": "Segment zvýraznený pomocou Color Highlights. Žiadny problém",
  "15.title.en": "WME Color Highlights: Recently edited",
  "15.title": "WME Color Highlights: Nedávno editované",
  "15.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "15.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "16.title.en": "WME Color Highlights: Road rank",
  "16.title": "WME Color Highlights: Kategórie ciest",
  "16.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "16.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "17.title.en": "WME Color Highlights: No city",
  "17.title": "WME Color Highlights: Bez názvu mesta",
  "17.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "17.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "18.title.en": "WME Color Highlights: Time restriction / Highlighted road type",
  "18.title": "WME Color Highlights: Časové obmedzenie / Zvýraznené typy ciest",
  "18.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "18.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "19.title.en": "WME Color Highlights: No name",
  "19.title": "WME Color Highlights: Bez názvu",
  "19.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "19.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "20.title.en": "WME Color Highlights: Filter by city",
  "20.title": "WME Color Highlights: Filter podľa mesta",
  "20.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "20.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "21.title.en": "WME Color Highlights: Filter by city (alt. city)",
  "21.title": "WME Color Highlights: Filter podľa mesta (alt. mestá)",
  "21.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "21.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "22.title.en": "WME Color Highlights: Filter by editor",
  "22.title": "WME Color Highlights: Filter podľa editorov",
  "22.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "22.problem": "Segment zvýraznený pomocou WME Color Highlights. Žiadny problém",
  "23.title.en": "Unconfirmed road",
  "23.title": "Nepotvrdená ulica",
  "23.problem.en": "Each segment must minimally have the Country and State information",
  "23.problem": "Každý segment musí mať minimálne informácie o štáte a zemi",
  "23.solution.en": "Confirm the road by updating its details",
  "23.solution": "Potvrdenie cesty vďaka aktualizácii jej detailov",
  "24.title.en": "Might be incorrect city name (only available in the report)",
  "24.title": "Možnosť nekorektného názvu mesta (dostupné len v hlásení)",
  "24.problem.en": "The segment might have incorrect city name",
  "24.problem": "Segment môže mať nesprávny názov mesta",
  "24.solution.en": "Consider suggested city name and use this form to rename the city",
  "24.solution": "Zváž navrhnutý názov mesta a použi tento formulár pre jeho premenovanie",
  "25.title.en": "Unknown direction of drivable road",
  "25.title": "Neznámy smer jazdy na ceste",
  "25.problem.en": "'Unknown' road direction will not prevent routing on the road",
  "25.problem": "Neznámy smer cesty nezabráni vedeniu trasy po komunikácii",
  "25.solution.en": "Set the road direction",
  "25.solution": "Nastav smer cesty",
  "27.enabled": true,
  "27.title.en": "City name on Railroad",
  "27.title": "Názov mesta na ceste",
  "27.problem.en": "City name on the Railroad may cause a city smudge",
  "27.problem": "Názov mesta na železnici môže spôsobiť rozmazanie",
  "27.solution.en": "In the address properties check the 'None' box next to the city name and then click 'Apply'",
  "27.solution": "V parametroch adresy označ 'Nič' pre názov mesta a daj 'Použiť'",
  "28.title.en": "Street name on two-way Ramp",
  "28.title": "Názov ulice na obojsmernej Ramp",
  "28.problem.en": "If Ramp is unnamed, the name of a subsequent road will propagate backwards",
  "28.problem": "Ak je Rampa nepomenovaná, názov pokračujúcej komunikácie bude prevzatý z predchádzajúcej",
  "28.solution.en": "In the address properties check the 'None' box next to the street name and then click 'Apply'",
  "28.solution": "V parametroch adresy označ 'Žiadne' pre názov ulice a klikni na 'Použiť'",
  "29.title.en": "Street name on roundabout",
  "29.title": "Názov ulice na kruhovom objazde",
  "29.problem.en": "In Waze, we do not name roundabout segments",
  "29.problem": "Vo Waze, nedávame názvy segmentom kruhových objazdov",
  "29.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout",
  "29.solution": "V parametroch adresy označ 'Žiadne' pre názov ulice a klikni na 'Použiť', potom pridaj 'Junction' landmark na križovatku pre pomenovanie kruhového objazdu",
  "34.title.en": "Empty alternate street",
  "34.title": "Prázdna alternatívna ulica",
  "34.problem.en": "Alternate street name is empty",
  "34.problem": "Alternatívny názov uliceje prázdny",
  "34.solution.en": "Remove empty alternate street name",
  "34.solution": "Odstráň prázdny alternatívny názov ulice",
  "35.title.en": "Unterminated drivable road",
  "35.title": "Neukončená prejazdná komunikácia",
  "35.problem.en": "Waze will not route from the unterminated segment",
  "35.problem": "Waze nedá trasu z neukončeného segmentu",
  "35.solution.en": "Move the segment a bit so the terminating node will be added automatically",
  "35.solution": "Posuň ľahko segment, ukončovací uzol bude vložený automaticky",
  "36.title.en": "Node A: Unneeded (slow)",
  "36.title": "Uzol A: Nepotrebný (nezaujímavý)",
  "36.problem.en": "Adjacent segments at node A are identical",
  "36.problem": "Susediace segmenty v uzle A sú identické",
  "36.solution.en": "Select node A and press Delete key to join the segments",
  "36.solution": "Vyber uzol A a klávesou Delete vymaž uzol (segmenty sa spoja do jedného)",
  "37.title.en": "Node B: Unneeded (slow)",
  "37.title": "Uzol B: Nepotrebný (nezaujímavý)",
  "37.problem.en": "Adjacent segments at node B are identical",
  "37.problem": "Susediace segmenty v uzle B sú identické",
  "37.solution.en": "Select node B and press Delete key to join the segments",
  "37.solution": "Vyber uzol B a klávesou Delete vymaž uzol (segmenty sa spoja do jedného)",
  "38.title.en": "Expired segment restriction (slow)",
  "38.title": "Neplatné obmedzenie segmentu",
  "38.problem.en": "The segment has an expired restriction",
  "38.problem": "Segment má neplatné obmedzenie",
  "38.solution.en": "Click 'Edit restrictions' and delete the expired restriction",
  "38.solution": "Stlač 'Zobraziť obmedzenie' a vymaž neplatné obmedzenie",
  "39.title.en": "Expired turn restriction (slow)",
  "39.title": "Neplatné obmedzenie odbočenia",
  "39.problem.en": "The segment has a turn with an expired restriction",
  "39.problem": "Segment má odbočenie s neplatným obmedzením",
  "39.solution.en": "Click clock icon next to the yellow arrow and delete the expired restriction",
  "39.solution": "Klikni na ikonu hodín vedľa žltej šípky a vymaž neplatné obmedzenie",
  "41.title.en": "Node A: Reverse connectivity of drivable road",
  "41.title": "Uzol A: Opačné pripojenie na prejazdnú komunikáciu",
  "41.problem.en": "There is a turn which goes against the directionality of the segment at node A",
  "41.problem": "Je tu povolené odbočenie, ktoré ide proti smeru jazdy segmentu v uzle A",
  "41.solution.en": "Make the segment 'Two-way', restrict all the turns at node A and then make the segment 'One way (A→B)' again",
  "41.solution": "Zadaj segment ako obojsmerný, uprav odbočenia v uzle A a potom zadaj jednosmerku z uzla A do uzla B",
  "42.title.en": "Node B: Reverse connectivity of drivable road",
  "42.title": "Uzol B: Opačné pripojenie na prejazdnú komunikáciu",
  "42.problem.en": "There is a turn which goes against the directionality of the segment at node B",
  "42.problem": "Je tu povolené odbočenie, ktoré ide proti smeru jazdy segmentu v uzle B",
  "42.solution.en": "Make the segment 'Two-way', restrict all the turns at node B and then make the segment 'One way (B→A)' again",
  "42.solution": "Zadaj segment ako obojsmerný, uprav odbočenia v uzle A a potom zadaj jednosmerku z uzla A do uzla B",
  "43.title.en": "Self connectivity",
  "43.title": "Pripojenie na samého seba",
  "43.problem.en": "The segment is connected back to itself",
  "43.problem": "Segment je pripojený sám k sebe",
  "43.solution.en": "Split the segment into THREE pieces",
  "43.solution": "Rozdeľ segment na TRI časti",
  "44.title.en": "No outward connectivity",
  "44.title": "Žiadne vonkajšie pripojenie",
  "44.problem.en": "The drivable segment has no single outward turn enabled",
  "44.problem": "Segment nemá žiadne vonkajšie pripojenie",
  "44.solution.en": "Enable at least one outward turn from the segment",
  "44.solution": "Povol aspoň jedno odbočenie zo segmentu",
  "45.title.en": "No inward connectivity",
  "45.title": "Žiadne vnútorné pripojenie",
  "45.problem.en": "The drivable non-private segment has no single inward turn enabled",
  "45.problem": "Verejný segment nemá povolené žiadne odbočenie ",
  "45.solution.en": "Select an adjacent segment and enable at least one turn to the segment",
  "45.solution": "Vyber susedný segment a povol aspoň jedno odbočenie na segmente",
  "46.title.en": "Node A: No inward connectivity of drivable road (slow)",
  "46.title": "Uzol A: Neexistuje vnútorné napojenie na prejazdnú komunikáciu",
  "46.problem.en": "The drivable non-private segment has no single inward turn enabled at node A",
  "46.problem": "Verejný segment nemá povolené žiadne odbočenie v uzle A",
  "46.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node A",
  "46.solution": "Vyber susedný segment a povol aspoň jedno odbočenie na segmente v uzle A",
  "47.title.en": "Node B: No inward connectivity of drivable road (slow)",
  "47.title": "Uzol B: Neexistuje vnútorné napojenie na prejazdnú komunikáciu",
  "47.problem.en": "The drivable non-private segment has no single inward turn enabled at node B",
  "47.problem": "Verejný segment nemá povolené žiadne odbočenie v uzle B",
  "47.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node B",
  "47.solution": "Vyber susedný segment a povol aspoň jedno odbočenie na segmente v uzle B",
  "48.title.en": "Two-way drivable roundabout segment",
  "48.title": "Obojsmerný kruhový objazd",
  "48.problem.en": "The drivable roundabout segment is bidirectional",
  "48.problem": "Kruhový objazd je obojsmerný",
  "48.solution.en": "Redo the roundabout",
  "48.solution": "Uprav kruhový objazd",
  "50.title.en": "No connectivity on roundabout (slow)",
  "50.title": "Žiadne pripojenie na kruhový objazd",
  "50.problem.en": "The drivable roundabout segment has no connectivity with adjacent roundabout segment",
  "50.problem": "Kruhový objazd nemá pripojenie na priľahlý kruhový objazd",
  "50.solution.en": "Enable a turn to the adjacent segment or redo the roundabout",
  "50.solution": "Umožni odbočenie na susedný segment alebo prerob kruhový objazd",
  "52.enabled": true,
  "52.title.en": "Too long street name",
  "52.title": "Príliš dlhý názov ulice",
  "52.problem.en": "The name of the drivable segment is more than ${n} letters long and it is not a Ramp",
  "52.problem": "Názov segmentu je dlhší ako ${n} znakov a nie je to Rampa",
  "52.solution.en": "Consider an abbreviation for the street name",
  "52.solution": "Zváž skratku pre názov ulice",
  "73.enabled": true,
  "73.title.en": "Too short street name",
  "73.title": "Príliš krátky názov ulice",
  "73.problem.en": "The street name is less than ${n} letters long and it is not a highway",
  "73.problem": "Názov segmentu je kratší ako ${n} znakov a nie je to diaľnica",
  "73.solution.en": "Correct the street name",
  "73.solution": "Oprav názov ulice",
  "77.title.en": "Dead-end U-turn",
  "77.title": "Otočenie v jednosmerke",
  "77.problem.en": "The drivable dead-end road has a U-turn enabled",
  "77.problem": "Jednosmerná komunikacia má povolené otočenie do protismeru",
  "77.solution.en": "Disable U-turn",
  "77.solution": "Zakázať otočenie do protismeru",
  "78.title.en": "Same endpoints drivable segments (slow)",
  "78.title": "Rovnaké koncové body segmentov",
  "78.problem.en": "Two drivable segments share the same two endpoints",
  "78.problem": "Dva segmenty sdieľajú rovnaké dva koncové body",
  "78.solution.en": "Split the segment. You might also remove one of the segments if they are identical",
  "78.solution": "Rozdeľ segmnet. Taktiež môžeš jeden zo segmentov odstrániť, ak sú identické",
  "87.title.en": "Node A: Multiple outgoing segments at roundabout",
  "87.title": "Uzol A: Viac výjazdov na kruhovom objazde",
  "87.problem.en": "The drivable roundabout node A has more than one outgoing segment connected",
  "87.problem": "Kruhový objazd v uzle A má pripojených viac ako jeden výjazd",
  "87.solution.en": "Redo the roundabout",
  "87.solution": "Uprav kruhový objazd",
  "90.enabled": true,
  "90.title.en": "Two-way Freeway segment",
  "90.title": "Obojsmerný dialničný segment",
  "90.problem.en": "Most of the Freeways are split into two one-way roads, so this two-way segment might be a mistake",
  "90.problem": "Väčšina dialnic je rozdelená na dve jednosmerné komunikácie, takže tento obojsmerný semgent môže byť omyl",
  "90.solution.en": "Check Freeway direction",
  "90.solution": "Skontroluj smer diaľnice",
  "99.title.en": "U-turn at roundabout entrance (slow)",
  "99.title": "Otočenie do protismeru na vjazde do kruhového objazdu",
  "99.problem.en": "The roundabout entrance segment has a U-turn enabled",
  "99.problem": "Vjazd na kruhový objazd má povolené otočenie do protismeru",
  "99.solution.en": "Disable U-turn",
  "99.solution": "Zruš otočenie do protismeru",
  "101.title.en": "Closed road (only available in the report)",
  "101.title": "Uzavretá komunikácia (dostupné len v hlásení)",
  "101.problem.en": "The segment is marked as closed",
  "101.problem": "Segment je označený ako uzavretý",
  "101.solution.en": "If the construction is done, restore the segment connectivity and remove the suffix",
  "101.solution": "Ak je stavba dokončená, obnov pripojenie segmentu a odstráň jeho 'suffix'",
  "102.title.en": "Node A: No outward connectivity of drivable road (slow)",
  "102.title": "Uzol A: Bez vonkajšieho pripojenia na prejazdnú komunikáciu",
  "102.problem.en": "The drivable segment has no single outward turn enabled at node A",
  "102.problem": "Prejazdný segment nemá povolené vonkajšie odbočenie v uzle A",
  "102.solution.en": "Enable at least one outward turn from the segment at node A",
  "102.solution": "Povol najmenej jedno vonkajšie odbočenie zo segmentu v uzle A",
  "103.title.en": "Node B: No outward connectivity of drivable road (slow)",
  "103.title": "Uzol B: Bez vonkajšieho pripojenia na prejazdnú komunikáciu",
  "103.problem.en": "The drivable segment has no single outward turn enabled at node B",
  "103.problem": "Prejazdný segment nemá povolené vonkajšie odbočenie v uzle B",
  "103.solution.en": "Enable at least one outward turn from the segment at node B",
  "103.solution": "Povol najmenej jedno vonkajšie odbočenie zo segmentu v uzle B",
  "104.title.en": "Railroad used for comments",
  "104.title": "Železnica použitá pre komentár",
  "104.problem.en": "The Railroad segment is probably used as a map comment",
  "104.problem": "Segment železnice je pravdepodobne použitý ako mapový komentár",
  "104.solution.en": "Remove the comment as Railroads will be added to the client display",
  "104.solution": "Odstráň segment železnice, ktorý je použitý ako mapový komentár",
  "105.enabled": true,
  "105.title.en": "Walking Trail instead of a Railroad",
  "105.title": "Chodník namiesto železnice",
  "105.problem.en": "The Walking Trail segment with elevation -5 is probably used instead of a Railroad",
  "105.problem": "Segment s výškou -5 je pravdepodobne použitý namiesto železnice",
  "105.solution.en": "Change road type to Railroad as Railroads will be added to the client display",
  "105.solution": "Skontroluj nastavenia pre tento segment",
  "107.title.en": "Node A: No connection (slow)",
  "107.title": "Uzol A: Bez pripojenia",
  "107.problem.en": "The node A of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "107.problem": "Uzol A prejazdného segmentu je bližšie ako 5m od ďalšieho prejazdného segmentu, ale nie je pripojený pomocou križovatky",
  "107.solution.en": "Drag the node A to the nearby segment so that it touches or move it a bit further away",
  "107.solution": "Posuň uzol A k najbližšiemu segmentu tak, že sa ho dotkne alebo ho kúsok presiahne",
  "108.title.en": "Node B: No connection (slow)",
  "108.title": "Uzol B: Bez pripojenia",
  "108.problem.en": "The node B of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "108.problem": "Uzol B prejazdného segmentu je bližšie ako 5m od ďalšieho prejazdného segmentu, ale nie je pripojený pomocou križovatky",
  "108.solution.en": "Drag the node B to the nearby segment so that it touches or move it a bit further away",
  "108.solution": "Posuň uzol B k najbližšiemu segmentu tak, že sa ho dotkne alebo ho kúsok presiahne",
  "109.title.en": "Too short segment",
  "109.title": "Príliš krátky segment",
  "109.problem.en": "The drivable non-terminal segment is less than ${n}m long so it is hard to see it on the map and it can cause routing problems",
  "109.problem": "Dĺžka segmentu je menej ako ${n}m takže ho nemusí byť vidno na mape a to môže spôsobiť problémy pri navigovaní",
  "109.solution.en": "Increase the length, or remove the segment, or join it with one of the adjacent segments",
  "109.solution": "Predĺž alebo odstráň segment, prípadne ho spoj s niektorým susediacim segmentom",
  "112.title.en": "Too long Ramp name",
  "112.title": "Príliš dlhý názov Rampy",
  "112.problem.en": "The Ramp name is more than ${n} letters long",
  "112.problem": "Názov Rampy je dlší ako ${n} znakov",
  "112.solution.en": "Shorten the Ramp name",
  "112.solution": "Skráť názov Rampy",
  "114.enabled": false,
  "114.title.en": "Node A: Non-drivable connected to drivable (slow)",
  "114.title": "Uzol A: Neprejazdný segment je pripojený na prejazdný",
  "114.problem.en": "The non-drivable segment makes a junction with a drivable at node A",
  "114.problem": "Neprejazdný segment vytvoril križovatku s prejazdným v uzle A",
  "114.solution.en": "Disconnect node A from all of the drivable segments",
  "114.solution": "Odpoj uzol A od vsetkých prejazdných segmentov",
  "115.enabled": false,
  "115.title.en": "Node B: Non-drivable connected to drivable (slow)",
  "115.title": "Uzol B: Neprejazdný segment je pripojený na prejazdný",
  "115.problem.en": "The non-drivable segment makes a junction with a drivable at node B",
  "115.problem": "Neprejazdný segment vytvoril križovatku s prejazdným v uzle B",
  "115.solution.en": "Disconnect node B from all of the drivable segments",
  "115.solution": "Odpoj uzol B od vsetkých prejazdných segmentov",
  "116.title.en": "Out of range elevation",
  "116.title": "Mimo rozsah výšky",
  "116.problem.en": "The segment elevation is out of range",
  "116.problem": "Výška segmentu je mimo rozsah",
  "116.solution.en": "Correct the elevation",
  "116.solution": "Oprav výšku segmentu",
  "117.title.en": "Obsolete CONST ZN marker",
  "117.title": "Zastarané 'CONST ZN' značka",
  "117.problem.en": "The segment is marked with obsolete CONST ZN suffix",
  "117.problem": "Segment je označený zastaralou 'CONST ZN' značkou",
  "117.solution.en": "Change CONST ZN to (closed)",
  "117.solution": "Zmena CONST ZN na (uzavreté)",
  "118.title.en": "Node A: Overlapping segments (slow)",
  "118.title": "Uzol A: Presahuje segmenty",
  "118.problem.en": "The segment is overlapping with the adjacent segment at node A",
  "118.problem": "Segment sa prekrýva so susedným segmentom v bode A",
  "118.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node A",
  "118.solution": "Rozlož segmenty na dva alebo vymaž nepotrebné body alebo vymaž duplicitný segment v uzle A",
  "119.title.en": "Node B: Overlapping segments (slow)",
  "119.title": "Uzol B: Presahuje segmenty",
  "119.problem.en": "The segment is overlapping with the adjacent segment at node B",
  "119.problem": "Segment sa prekrýva so susedným segmentom v bode B",
  "119.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node B",
  "119.solution": "Rozlož segmenty na dva alebo vymaž nepotrebné body alebo vymaž duplicitný segment v uzle B",
  "120.title.en": "Node A: Too sharp turn (slow)",
  "120.title": "Uzol A: Veľmi ostrá zákruta (pomalé)",
  "120.problem.en": "The drivable segment has a very acute turn at node A",
  "120.problem": "Segment má veľmi ostré zatočenie v uzle A",
  "120.solution.en": "Disable the sharp turn at node A or spread the segments at 30°",
  "120.solution": "Zruš ostrú zákrutu v uzle A alebo ju uprav minimálne na 30°",
  "121.title.en": "Node B: Too sharp turn (slow)",
  "121.title": "Uzol B: Veľmi ostrá zákruta (pomalé)",
  "121.problem.en": "The drivable segment has a very acute turn at node B",
  "121.problem": "Segment má veľmi ostré zatočenie v uzle B",
  "121.solution.en": "Disable the sharp turn at node B or spread the segments at 30°",
  "121.solution": "Zruš ostrú zákrutu v uzle A alebo ju uprav minimálne na 30°",
  "128.title.en": "User-defined custom check (green)",
  "128.title": "Užívateľom definované kontroly (zelená)",
  "128.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "128.problem": "Niektoré parametre segmentu sú zhodné s užívateľom definovanými kritériami (pozri Nastavenia→Vlastné)",
  "128.solution.en": "Solve the issue",
  "128.solution": "Vyriešiť chybu",
  "129.title.en": "User-defined custom check (blue)",
  "129.title": "Užívateľom definované kontroly (modrá)",
  "129.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "129.problem": "Niektoré parametre segmentu sú zhodné s užívateľom definovanými kritériami (pozri Nastavenia→Vlastné)",
  "129.solution.en": "Solve the issue",
  "129.solution": "Vyriešiť chybu",
  "150.enabled": true,
  "150.params": {
    "n": 2
  },
  "150.problemLink": "F:t=64980&p=572847#p572847",
  "150.title.en": "No lock on Freeway",
  "150.title": "Bez uzamknutia pre 'Freeway'",
  "150.problem.en": "The Freeway segment should be locked at least to Lvl ${n}",
  "150.problem": "Segment 'Freeway' môže byť uzamknutý s minimálnym Lvl ${n}",
  "150.solution.en": "Lock the segment",
  "150.solution": "Uzamknúť segment",
  "151.enabled": true,
  "151.params": {
    "n": 2
  },
  "151.problemLink": "F:t=64980&p=572847#p572847",
  "151.title.en": "No lock on Major Highway",
  "151.title": "Bez uzamknutia pre cestu I.triedy",
  "151.problem.en": "The Major Highway segment should be locked at least to Lvl ${n}",
  "151.problem": "Segment cesty I.triedy môže byť uzamknutý s minimálnym Lvl ${n}",
  "151.solution.en": "Lock the segment",
  "151.solution": "Uzamknúť segment",
  "152.enabled": true,
  "152.params": {
    "n": 2
  },
  "152.problemLink": "F:t=64980&p=572847#p572847",
  "152.title.en": "No lock on Minor Highway",
  "152.title": "Bez uzamknutia pre cestu II.triedy",
  "152.problem.en": "The Minor Highway segment should be locked at least to Lvl ${n}",
  "152.problem": "Segment cesty II.triedy môže byť uzamknutý s minimálnym Lvl ${n}",
  "152.solution.en": "Lock the segment",
  "152.solution": "Uzamknúť segment",
  "170.enabled": true,
  "170.params": {
    "regexp": "/^(?!(námestie|nám\\.|nábrežie|nábr\\.|trieda|tr\\.|tunel|most|ulica|ul\\.|sídl\\.|sídlisko|park|sad|sady) [^a-z])[a-z]/"
  },
  "170.title.en": "Lowercase street name",
  "170.title": "Malé písmeno pre názov ulice",
  "170.problem.en": "The street name starts with a lowercase word",
  "170.problem": "Názov ulice začína malým písmenom",
  "170.solution.en": "Correct lettercase in the street name",
  "170.solution": "Oprav písmená v názve ulice",
  "172.title.en": "Unneeded spaces in street name",
  "172.title": "Nepotrebná medzera v názve ulice",
  "172.problem.en": "Leading/trailing/double space in the street name",
  "172.problem": "Medzery v názve ulice (pred/za/dvojitá)",
  "172.solution.en": "Remove unneeded spaces from the street name",
  "172.solution": "Odstráň nepotrebné medzery z názvu ulice",
  "173.title.en": "No space before/after street abbreviation",
  "173.title": "Nieje mezera pred/za skratkou ulice",
  "173.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the street name",
  "173.problem": "Nieje medzera pred ('1943r.') alebo za ('st.Jan') skratkou v názve ulice",
  "173.solution.en": "Add a space before/after the abbreviation",
  "173.solution": "Pridať medzeru pred/za skratku",
  "175.title.en": "Empty street name",
  "175.title": "Prázdne meno ulice",
  "175.problem.en": "The street name has only space characters or a dot",
  "175.problem": "Názov ulice obsahuje medzery, písmená alebo bodky",
  "175.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' OR set a proper street name",
  "175.solution": "V nastaveniach adresy označ 'Žiadne' a stlač 'Uložiť' ALEBO nastav správny názov ulice",
  "190.title.en": "Lowercase city name",
  "190.title": "Meno mesta malými písmenami",
  "190.problem.en": "The city name starts with a lowercase letter",
  "190.problem": "Názov mesta začína malým písmenom",
  "190.solution.en": "Use this form to rename the city",
  "190.solution": "Použi tento formulár pre zmenu názvu mesta",
  "192.title.en": "Unneeded spaces in city name",
  "192.title": "Nepotrebné medzery v nazve mesta",
  "192.problem.en": "Leading/trailing/double space in the city name",
  "192.problem": "Medzery v názve mesta (pred/za/dvojité)",
  "192.solution.en": "Use this form to rename the city",
  "192.solution": "Použi tento formulár pre zmenu názvu mesta",
  "193.title.en": "No space before/after city abbreviation",
  "193.title": "Nieje medzera pred/za skratkou mesta",
  "193.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the city name",
  "193.problem": "Nieje medzera pred ('1943r.') alebo za ('st.Jan') skratkou v názve mesta",
  "193.solution.en": "Use this form to rename the city",
  "193.solution": "Použi tento formulár pre zmenu názvu mesta",
  "200.title.en": "Node A: Unconfirmed turn on minor road",
  "200.title": "Uzol A: Nepotvrdené odbočenie na vedľajšiu cestu",
  "200.problem.en": "The minor drivable segment has an unconfirmed (soft) turn at node A",
  "200.problem": "Vedľajší prejazdný segment má nepotvrdené odbočenie v uzle A",
  "200.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "200.solution": "Klikni na odbočenie označené fialovým otáznikom pre jeho potvrdenie. Pozn.: možno bude potrebné určiť segment ako obojsmerný pre zobrazenie týchto odbočení",
  "201.title.en": "Node A: Unconfirmed turn on primary road",
  "201.title": "Uzol A: Nepotvrdené odbočenie na hlavnú cestu",
  "201.problem.en": "The primary segment has an unconfirmed (soft) turn at node A",
  "201.problem": "Hlavný segment má nepotvrdené odbočenie v uzle A",
  "201.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "201.solution": "Klikni na odbočenie označené fialovým otáznikom pre jeho potvrdenie. Pozn.: možno bude potrebné určiť segment ako obojsmerný pre zobrazenie týchto odbočení"
};

